// Copyright (c) 2026 Ztry8 (AslanD)
// Licensed under the Apache License, Version 2.0 (the "License");
// You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0

use std::collections::HashMap;
use std::fmt::Write as _;

use crate::{
    lexer::Token,
    parser::{AstKind, AstNode, Cast, ElseBlock},
    types::{ReturnType, TypesCheck},
};

pub fn compile(ast: &[AstNode]) -> Result<String, String> {
    let mut ctx = ProgramCtx::new();

    for node in ast {
        if let AstKind::Func {
            name,
            args,
            return_type,
            ..
        } = &node.kind
        {
            ctx.funcs
                .insert(name.clone(), (args.clone(), return_type.clone()));
        }
    }

    let mut const_decls = String::new();
    let mut const_names: HashMap<String, TypesCheck> = HashMap::new();
    emit_builtin_constants(&mut const_decls, &mut const_names);

    for node in ast {
        if let AstKind::VarDecl {
            name,
            type_,
            value,
            is_const,
        } = &node.kind
        {
            if !*is_const {
                return Err(format!(
                    "internal codegen error: top-level non-const variable '{name}'"
                ));
            }
            emit_top_level_const(&mut const_decls, &mut const_names, name, type_, value)?;
        }
    }

    ctx.const_names = const_names;

    let mut func_decls = String::new();
    let mut func_defs = String::new();

    for node in ast {
        if let AstKind::Func {
            name,
            body,
            args,
            return_type,
        } = &node.kind
        {
            let sig = render_func_signature(name, args, return_type);
            let _ = writeln!(func_decls, "{sig};");

            let def = compile_function(&ctx, name, args, return_type, body)?;
            func_defs.push_str(&def);
            func_defs.push('\n');
        }
    }

    let mut out = String::new();
    let _ = writeln!(
        out,
        "/* Generated by Cylium c_codegen. Do not edit by hand. */"
    );
    let _ = writeln!(out, "#include \"runtime.h\"");
    let _ = writeln!(out, "#include <string.h>\n");
    out.push_str(&const_decls);
    out.push('\n');
    out.push_str(&func_decls);
    out.push('\n');
    out.push_str(&func_defs);

    let _ = writeln!(
        out,
        "int main(void)\n{{\n    return (int)cyl_f_main();\n}}\n"
    );

    Ok(out)
}

struct ProgramCtx {
    funcs: HashMap<String, (Vec<(String, TypesCheck)>, ReturnType)>,
    const_names: HashMap<String, TypesCheck>,
}

impl ProgramCtx {
    fn new() -> Self {
        Self {
            funcs: HashMap::new(),
            const_names: HashMap::new(),
        }
    }
}

struct FuncCtx<'a> {
    prog: &'a ProgramCtx,
    vars: HashMap<String, TypesCheck>,
    hoisted: Vec<(String, TypesCheck)>,
    heap_vars: Vec<(String, TypesCheck)>,
    tmp_counter: usize,
}

fn c_alive_name(name: &str) -> String {
    format!("cyl_alive_{}", c_name(name))
}

impl<'a> FuncCtx<'a> {
    fn new(prog: &'a ProgramCtx) -> Self {
        Self {
            prog,
            vars: HashMap::new(),
            hoisted: Vec::new(),
            heap_vars: Vec::new(),
            tmp_counter: 0,
        }
    }

    fn fresh_tmp(&mut self, prefix: &str) -> String {
        let n = self.tmp_counter;
        self.tmp_counter += 1;
        format!("cyl_tmp_{prefix}_{n}")
    }

    fn declare(&mut self, name: &str, ty: TypesCheck) {
        if !self.vars.contains_key(name) {
            self.hoisted.push((c_name(name), ty.clone()));
            if is_heap_type(&ty) {
                self.heap_vars.push((name.to_owned(), ty.clone()));
            }
        }
        self.vars.insert(name.to_owned(), ty);
    }

    fn lookup(&self, name: &str) -> Result<TypesCheck, String> {
        if let Some(t) = self.vars.get(name) {
            return Ok(t.clone());
        }
        if let Some(t) = self.prog.const_names.get(name) {
            return Ok(t.clone());
        }
        Err(format!(
            "internal codegen error: unknown identifier '{name}'"
        ))
    }

    fn is_const(&self, name: &str) -> bool {
        !self.vars.contains_key(name) && self.prog.const_names.contains_key(name)
    }

    fn emit_drop_glue(&self, out: &mut String, pad: &str, skip: Option<&str>) {
        for (name, ty) in &self.heap_vars {
            if skip == Some(name.as_str()) {
                continue;
            }
            let free_fn = heap_free_fn(ty);
            let cname = c_name(name);
            let alive = c_alive_name(name);
            let _ = writeln!(
                out,
                "{pad}if ({alive}) {{ {free_fn}({cname}); {alive} = CYL_FALSE; }}"
            );
        }
    }
}

fn c_name(name: &str) -> String {
    format!("cyl_v_{name}")
}

fn c_func_name(name: &str) -> String {
    format!("cyl_f_{name}")
}

fn c_const_name(name: &str) -> String {
    format!("cyl_c_{name}")
}

fn c_type(t: &TypesCheck) -> &'static str {
    match t {
        TypesCheck::Int => "cyl_int",
        TypesCheck::Float => "double",
        TypesCheck::Boolean => "cyl_bool",
        TypesCheck::String => "CylString",
        TypesCheck::Array(inner) => match inner.as_ref() {
            TypesCheck::Int => "CylArrayInt",
            TypesCheck::Float => "CylArrayFloat",
            TypesCheck::Boolean => "CylArrayBool",
            other => panic!("unsupported array element type in codegen: {other:?}"),
        },
    }
}

fn c_return_type(t: &ReturnType) -> &'static str {
    match t {
        ReturnType::Void => "void",
        ReturnType::Int => "cyl_int",
        ReturnType::Float => "double",
        ReturnType::Boolean => "cyl_bool",
        ReturnType::String => "CylString",
        ReturnType::Array(inner) => match inner.as_ref() {
            ReturnType::Int => "CylArrayInt",
            ReturnType::Float => "CylArrayFloat",
            ReturnType::Boolean => "CylArrayBool",
            other => panic!("unsupported array element type in codegen: {other:?}"),
        },
    }
}

fn return_type_to_check(t: &ReturnType) -> TypesCheck {
    match t {
        ReturnType::Void => unreachable!("Void has no expression-position type"),
        ReturnType::Int => TypesCheck::Int,
        ReturnType::Float => TypesCheck::Float,
        ReturnType::Boolean => TypesCheck::Boolean,
        ReturnType::String => TypesCheck::String,
        ReturnType::Array(inner) => TypesCheck::Array(Box::new(return_type_to_check(inner))),
    }
}

fn is_heap_type(t: &TypesCheck) -> bool {
    matches!(t, TypesCheck::String | TypesCheck::Array(_))
}

fn array_elem_suffix(elem: &TypesCheck) -> &'static str {
    match elem {
        TypesCheck::Int => "int",
        TypesCheck::Float => "float",
        TypesCheck::Boolean => "bool",
        other => panic!("unsupported array element type in codegen: {other:?}"),
    }
}

fn heap_free_fn(ty: &TypesCheck) -> &'static str {
    match ty {
        TypesCheck::String => "cyl_string_free",
        TypesCheck::Array(elem) => match array_elem_suffix(elem) {
            "int" => "cyl_array_int_free",
            "float" => "cyl_array_float_free",
            "bool" => "cyl_array_bool_free",
            _ => unreachable!(),
        },
        TypesCheck::Int | TypesCheck::Float | TypesCheck::Boolean => {
            unreachable!("heap_free_fn called on a non-heap type")
        }
    }
}

fn emit_builtin_constants(out: &mut String, names: &mut HashMap<String, TypesCheck>) {
    let _ = writeln!(
        out,
        "static const double {} = 3.14159265358979323846;",
        c_const_name("PI")
    );
    let _ = writeln!(
        out,
        "static const double {} = 2.71828182845904523536;",
        c_const_name("E")
    );
    names.insert("PI".to_owned(), TypesCheck::Float);
    names.insert("E".to_owned(), TypesCheck::Float);

    let platform_consts = [
        ("IS_LINUX", "__linux__"),
        ("IS_MACOS", "__APPLE__"),
        ("IS_WINDOWS", "_WIN32"),
        ("IS_X86_64", "__x86_64__"),
        ("IS_ARM64", "__aarch64__"),
    ];
    for (name, cfg_macro) in platform_consts {
        let _ = writeln!(out, "#if defined({cfg_macro})");
        let _ = writeln!(
            out,
            "static const cyl_bool {} = CYL_TRUE;",
            c_const_name(name)
        );
        let _ = writeln!(out, "#else");
        let _ = writeln!(
            out,
            "static const cyl_bool {} = CYL_FALSE;",
            c_const_name(name)
        );
        let _ = writeln!(out, "#endif");
        names.insert(name.to_owned(), TypesCheck::Boolean);
    }
}

fn emit_top_level_const(
    out: &mut String,
    names: &mut HashMap<String, TypesCheck>,
    name: &str,
    type_: &TypesCheck,
    value: &AstKind,
) -> Result<(), String> {
    match (type_, value) {
        (TypesCheck::Int, AstKind::Int(v)) => {
            let _ = writeln!(out, "static const cyl_int {} = {v}L;", c_const_name(name));
        }
        (TypesCheck::Float, AstKind::Float(v)) => {
            let _ = writeln!(
                out,
                "static const double {} = {};",
                c_const_name(name),
                format_c_float(*v)
            );
        }
        (TypesCheck::Boolean, AstKind::Boolean(v)) => {
            let _ = writeln!(
                out,
                "static const cyl_bool {} = {};",
                c_const_name(name),
                if *v { "CYL_TRUE" } else { "CYL_FALSE" }
            );
        }
        (TypesCheck::String, AstKind::String(v)) => {
            let escaped = escape_c_string(v);
            let _ = writeln!(
                out,
                "static char {}_buf[] = \"{escaped}\";",
                c_const_name(name)
            );
            let _ = writeln!(
                out,
                "static const CylString {} = {{ {}_buf, {} }};",
                c_const_name(name),
                c_const_name(name),
                v.len()
            );
        }
        _ => {
            return Err(format!(
                "codegen limitation: top-level const '{name}' must be a literal of its declared type"
            ));
        }
    }

    names.insert(name.to_owned(), type_.clone());
    Ok(())
}

fn escape_c_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for b in s.bytes() {
        match b {
            b'\\' => out.push_str("\\\\"),
            b'"' => out.push_str("\\\""),
            b'\n' => out.push_str("\\n"),
            b'\r' => out.push_str("\\r"),
            b'\t' => out.push_str("\\t"),
            0x20..=0x7e => out.push(b as char),
            _ => {
                let _ = write!(out, "\\x{b:02x}\"\"");
            }
        }
    }
    out
}

fn format_c_float(v: f64) -> String {
    if v.is_infinite() {
        return if v > 0.0 {
            "(1.0/0.0)".to_owned()
        } else {
            "(-1.0/0.0)".to_owned()
        };
    }
    if v.is_nan() {
        return "(0.0/0.0)".to_owned();
    }
    let s = format!("{v:?}");
    if s.contains('.') || s.contains('e') || s.contains("inf") || s.contains("NaN") {
        s
    } else {
        format!("{s}.0")
    }
}

fn render_func_signature(
    name: &str,
    args: &[(String, TypesCheck)],
    return_type: &ReturnType,
) -> String {
    let params = if args.is_empty() {
        "void".to_owned()
    } else {
        args.iter()
            .map(|(n, t)| format!("{} {}", c_type(t), c_name(n)))
            .collect::<Vec<_>>()
            .join(", ")
    };
    format!(
        "{} {}({})",
        c_return_type(return_type),
        c_func_name(name),
        params
    )
}

fn compile_function(
    prog: &ProgramCtx,
    name: &str,
    args: &[(String, TypesCheck)],
    return_type: &ReturnType,
    body: &[AstNode],
) -> Result<String, String> {
    let mut fctx = FuncCtx::new(prog);

    for (pname, ptype) in args {
        fctx.vars.insert(pname.clone(), ptype.clone());
        if is_heap_type(ptype) {
            fctx.heap_vars.push((pname.clone(), ptype.clone()));
        }
    }

    let mut body_code = String::new();
    for node in body {
        compile_stmt(&mut fctx, &mut body_code, &node.kind, 1)?;
    }

    let mut out = String::new();
    let sig = render_func_signature(name, args, return_type);
    let _ = writeln!(out, "{sig}\n{{");

    for (cname, ty) in &fctx.hoisted {
        let _ = writeln!(out, "    {} {};", c_type(ty), cname);
    }
    for (hvar_name, _) in &fctx.heap_vars {
        let _ = writeln!(out, "    cyl_bool {};", c_alive_name(hvar_name));
    }
    if !fctx.hoisted.is_empty() || !fctx.heap_vars.is_empty() {
        out.push('\n');
    }

    for (pname, ptype) in args {
        if is_heap_type(ptype) {
            let _ = writeln!(out, "    {} = CYL_TRUE;", c_alive_name(pname));
        }
    }
    for (lname, _) in &fctx.heap_vars {
        if args.iter().any(|(pname, _)| pname == lname) {
            continue;
        }
        let _ = writeln!(out, "    {} = CYL_FALSE;", c_alive_name(lname));
    }
    out.push('\n');

    out.push_str(&body_code);

    if matches!(return_type, ReturnType::Void) {
        fctx.emit_drop_glue(&mut out, "    ", None);
    }

    if !matches!(return_type, ReturnType::Void) {
        let _ = writeln!(
            out,
            "    cyl_panic(\"unreachable: function fell through without returning\");"
        );
        let _ = writeln!(out, "    {{");
        let _ = writeln!(out, "        {} cyl_dummy_ret;", c_return_type(return_type));
        let _ = writeln!(
            out,
            "        memset(&cyl_dummy_ret, 0, sizeof(cyl_dummy_ret));"
        );
        let _ = writeln!(out, "        return cyl_dummy_ret;");
        let _ = writeln!(out, "    }}");
    }

    let _ = writeln!(out, "}}");
    Ok(out)
}

fn ind(level: usize) -> String {
    "    ".repeat(level)
}

fn compile_return_value(
    fctx: &mut FuncCtx,
    out: &mut String,
    pad: &str,
    expr: &AstKind,
) -> Result<(), String> {
    let (ty, code) = compile_expr(fctx, expr)?;

    let returning_array_var = match (&ty, expr) {
        (TypesCheck::Array(_), AstKind::Ident(name)) => Some(name.clone()),
        _ => None,
    };

    if let Some(name) = &returning_array_var {
        fctx.emit_drop_glue(out, pad, Some(name));
        let _ = writeln!(out, "{pad}return {code};");
        return Ok(());
    }

    if is_heap_type(&ty) {
        let tmp = fctx.fresh_tmp("ret");
        fctx.hoisted.push((tmp.clone(), ty.clone()));
        let _ = writeln!(out, "{pad}{tmp} = {code};");
        fctx.emit_drop_glue(out, pad, None);
        let _ = writeln!(out, "{pad}return {tmp};");
        return Ok(());
    }

    fctx.emit_drop_glue(out, pad, None);
    let _ = writeln!(out, "{pad}return {code};");
    Ok(())
}

fn compile_stmt(
    fctx: &mut FuncCtx,
    out: &mut String,
    node: &AstKind,
    level: usize,
) -> Result<(), String> {
    let pad = ind(level);
    match node {
        AstKind::Echo(expr) => {
            let (ty, code) = compile_expr(fctx, expr)?;
            let echo_fn = match ty {
                TypesCheck::Int => "cyl_echo_int",
                TypesCheck::Float => "cyl_echo_float",
                TypesCheck::Boolean => "cyl_echo_bool",
                TypesCheck::String => "cyl_echo_string",
                TypesCheck::Array(_) => {
                    return Err(
                        "codegen error: echo of an array is not supported by the runtime"
                            .to_owned(),
                    );
                }
            };

            if ty == TypesCheck::String {
                let _ = writeln!(out, "{pad}cyl_echo_and_free_string({code});");
            } else {
                let _ = writeln!(out, "{pad}{echo_fn}({code});");
            }
        }
        AstKind::Delete(name) => {
            let ty = fctx.lookup(name)?;
            if is_heap_type(&ty) {
                let free_fn = heap_free_fn(&ty);
                let _ = writeln!(out, "{pad}{free_fn}({});", c_name(name));
                let _ = writeln!(out, "{pad}{} = CYL_FALSE;", c_alive_name(name));
            }
        }
        AstKind::Exit(code) => {
            let _ = writeln!(out, "{pad}exit({code});");
        }
        AstKind::VarDecl {
            name, type_, value, ..
        } => {
            fctx.declare(name, type_.clone());
            let (_, code) = compile_expr(fctx, value)?;
            let _ = writeln!(out, "{pad}{} = {code};", c_name(name));
            if is_heap_type(type_) {
                let _ = writeln!(out, "{pad}{} = CYL_TRUE;", c_alive_name(name));
            }
        }
        AstKind::ArraySet {
            name,
            index,
            op,
            expr,
            elem_type,
        } => {
            compile_array_set(fctx, out, &pad, name, index, op, expr, elem_type)?;
        }
        AstKind::Return(None) => {
            fctx.emit_drop_glue(out, &pad, None);
            let _ = writeln!(out, "{pad}return;");
        }
        AstKind::Return(Some(expr)) => {
            compile_return_value(fctx, out, &pad, expr)?;
        }
        AstKind::FuncCall { name, args } => {
            compile_call_stmt(fctx, out, &pad, name, args)?;
        }
        AstKind::Assign {
            name,
            op,
            expr,
            var_type,
        } => {
            compile_assign(fctx, out, &pad, name, op, expr, var_type)?;
        }
        AstKind::Condition { expr, yes, no } => {
            let (_, cond_code) = compile_expr(fctx, expr)?;
            let _ = writeln!(out, "{pad}if ({cond_code}) {{");
            for n in yes {
                compile_stmt(fctx, out, &n.kind, level + 1)?;
            }
            match no {
                None => {
                    let _ = writeln!(out, "{pad}}}");
                }
                Some(ElseBlock::Else(else_body)) => {
                    let _ = writeln!(out, "{pad}}} else {{");
                    for n in else_body {
                        compile_stmt(fctx, out, &n.kind, level + 1)?;
                    }
                    let _ = writeln!(out, "{pad}}}");
                }
                Some(ElseBlock::ElseIf(elseif_node)) => {
                    let _ = writeln!(out, "{pad}}} else {{");
                    compile_stmt(fctx, out, &elseif_node.kind, level + 1)?;
                    let _ = writeln!(out, "{pad}}}");
                }
            }
        }
        AstKind::While { expr, body } => {
            let (_, cond_code) = compile_expr(fctx, expr)?;
            let _ = writeln!(out, "{pad}while ({cond_code}) {{");
            for n in body {
                compile_stmt(fctx, out, &n.kind, level + 1)?;
            }
            let _ = writeln!(out, "{pad}}}");
        }
        AstKind::For {
            var_name,
            start,
            end,
            step,
            body,
        } => {
            compile_for(fctx, out, &pad, level, var_name, start, end, step, body)?;
        }
        other => {
            return Err(format!(
                "internal codegen error: unexpected statement-position node {other:?}"
            ));
        }
    }
    Ok(())
}

fn compile_call_stmt(
    fctx: &mut FuncCtx,
    out: &mut String,
    pad: &str,
    name: &str,
    args: &[AstKind],
) -> Result<(), String> {
    let (ty, code) = compile_expr_call(fctx, name, args, true)?;
    if is_heap_type(&ty) {
        let free_fn = heap_free_fn(&ty);
        let _ = writeln!(out, "{pad}{free_fn}({code});");
    } else {
        let _ = writeln!(out, "{pad}{code};");
    }
    Ok(())
}

fn simple_compound_op(op: &Token) -> Option<&'static str> {
    match op {
        Token::PlusAssign => Some("+="),
        Token::MinusAssign => Some("-="),
        Token::MultiplyAssign => Some("*="),
        Token::DivideAssign => Some("/="),
        Token::ModAssign => Some("%="),
        Token::BitAndAssign => Some("&="),
        Token::BitOrAssign => Some("|="),
        Token::BitXorAssign => Some("^="),
        Token::BitRightAssign => Some(">>="),
        Token::BitLeftAssign => Some("<<="),
        _ => None,
    }
}

fn compile_assign(
    fctx: &mut FuncCtx,
    out: &mut String,
    pad: &str,
    name: &str,
    op: &Token,
    expr: &AstKind,
    var_type: &TypesCheck,
) -> Result<(), String> {
    if fctx.is_const(name) {
        return Err(format!(
            "internal codegen error: assignment to const '{name}' should have been rejected by the validator"
        ));
    }

    let cname = c_name(name);

    if *op == Token::Assign {
        let (_, code) = compile_expr(fctx, expr)?;
        if is_heap_type(var_type) {
            let free_fn = heap_free_fn(var_type);
            let _ = writeln!(out, "{pad}{free_fn}({cname});");
        }
        let _ = writeln!(out, "{pad}{cname} = {code};");
        return Ok(());
    }

    match var_type {
        TypesCheck::Int | TypesCheck::Float => {
            let c_op = simple_compound_op(op).ok_or_else(|| {
                format!("internal codegen error: unsupported compound op {op:?} for numeric type")
            })?;
            let (_, code) = compile_expr(fctx, expr)?;
            let _ = writeln!(out, "{pad}{cname} {c_op} {code};");
        }
        TypesCheck::String => {
            let (_, code) = compile_expr(fctx, expr)?;
            let new_val = match op {
                Token::PlusAssign => format!("cyl_string_concat({cname}, {code})"),
                Token::MultiplyAssign => format!("cyl_string_repeat({cname}, {code})"),
                _ => {
                    return Err(format!(
                        "internal codegen error: unsupported compound op {op:?} for string type"
                    ));
                }
            };
            let _ = writeln!(out, "{pad}{cname} = {new_val};");
        }
        TypesCheck::Array(_) | TypesCheck::Boolean => {
            return Err(format!(
                "internal codegen error: compound assignment on {var_type:?} should have been rejected by the validator"
            ));
        }
    }

    Ok(())
}

fn compile_array_set(
    fctx: &mut FuncCtx,
    out: &mut String,
    pad: &str,
    name: &str,
    index: &AstKind,
    op: &Token,
    expr: &AstKind,
    elem_type: &TypesCheck,
) -> Result<(), String> {
    let cname = c_name(name);
    let suffix = array_elem_suffix(elem_type);
    let get_fn = format!("cyl_array_{suffix}_get");
    let set_fn = format!("cyl_array_{suffix}_set");

    if *op == Token::Assign {
        let (_, val_code) = compile_expr(fctx, expr)?;
        let (_, idx_code) = compile_expr(fctx, index)?;
        let _ = writeln!(out, "{pad}{set_fn}({cname}, {idx_code}, {val_code});");
        return Ok(());
    }

    let (_, idx_code_read) = compile_expr(fctx, index)?;
    let current = format!("{get_fn}({cname}, {idx_code_read})");
    let (_, rhs) = compile_expr(fctx, expr)?;

    let new_val = match elem_type {
        TypesCheck::Float => match op {
            Token::PlusAssign => format!("({current} + {rhs})"),
            Token::MinusAssign => format!("({current} - {rhs})"),
            Token::MultiplyAssign => format!("({current} * {rhs})"),
            Token::DivideAssign => format!("({current} / {rhs})"),
            _ => {
                return Err(format!(
                    "internal codegen error: unsupported compound array op {op:?} for float element"
                ));
            }
        },
        TypesCheck::String => match op {
            Token::PlusAssign => format!("cyl_string_concat({current}, {rhs})"),
            _ => {
                return Err(format!(
                    "internal codegen error: unsupported compound array op {op:?} for string element"
                ));
            }
        },
        TypesCheck::Int => {
            let c_op = simple_compound_op(op).ok_or_else(|| {
                format!("internal codegen error: unsupported compound array op {op:?}")
            })?;
            let bin_op = &c_op[..c_op.len() - 1];
            format!("({current} {bin_op} {rhs})")
        }
        TypesCheck::Boolean | TypesCheck::Array(_) => {
            return Err(format!(
                "internal codegen error: compound array assignment on element type {elem_type:?} should have been rejected by the validator"
            ));
        }
    };

    let (_, idx_code_write) = compile_expr(fctx, index)?;
    let _ = writeln!(out, "{pad}{set_fn}({cname}, {idx_code_write}, {new_val});");
    Ok(())
}

fn compile_for(
    fctx: &mut FuncCtx,
    out: &mut String,
    pad: &str,
    level: usize,
    var_name: &str,
    start: &AstKind,
    end: &AstKind,
    step: &Option<AstKind>,
    body: &[AstNode],
) -> Result<(), String> {
    fctx.declare(var_name, TypesCheck::Int);
    let (_, start_code) = compile_expr(fctx, start)?;
    let _ = writeln!(out, "{pad}{} = {start_code};", c_name(var_name));

    let end_var = hidden_for_var("fe", var_name);
    fctx.declare(&end_var, TypesCheck::Int);
    let (_, end_code) = compile_expr(fctx, end)?;
    let _ = writeln!(out, "{pad}{} = {end_code};", c_name(&end_var));

    let step_var = match step {
        Some(step_expr) => {
            let sv = hidden_for_var("fs", var_name);
            fctx.declare(&sv, TypesCheck::Int);
            let (_, step_code) = compile_expr(fctx, step_expr)?;
            let _ = writeln!(out, "{pad}{} = {step_code};", c_name(&sv));
            Some(sv)
        }
        None => None,
    };

    let _ = writeln!(
        out,
        "{pad}while ({} <= {}) {{",
        c_name(var_name),
        c_name(&end_var)
    );
    for n in body {
        compile_stmt(fctx, out, &n.kind, level + 1)?;
    }
    let inner_pad = ind(level + 1);
    match &step_var {
        Some(sv) => {
            let _ = writeln!(out, "{inner_pad}{} += {};", c_name(var_name), c_name(sv));
        }
        None => {
            let _ = writeln!(out, "{inner_pad}{} += 1;", c_name(var_name));
        }
    }
    let _ = writeln!(out, "{pad}}}");
    Ok(())
}

fn hidden_for_var(tag: &str, var_name: &str) -> String {
    format!("__hidden_for_{tag}_{var_name}")
}

fn compile_expr(fctx: &mut FuncCtx, node: &AstKind) -> Result<(TypesCheck, String), String> {
    match node {
        AstKind::Ident(name) => {
            let ty = fctx.lookup(name)?;
            let cname = if fctx.is_const(name) {
                c_const_name(name)
            } else {
                c_name(name)
            };
            match &ty {
                TypesCheck::String => Ok((ty.clone(), format!("cyl_string_clone({cname})"))),
                TypesCheck::Array(_) => Ok((ty.clone(), cname)),
                _ => Ok((ty.clone(), cname)),
            }
        }

        AstKind::Int(v) => Ok((TypesCheck::Int, format!("{v}L"))),
        AstKind::Float(v) => Ok((TypesCheck::Float, format_c_float(*v))),
        AstKind::Boolean(v) => Ok((
            TypesCheck::Boolean,
            (if *v { "CYL_TRUE" } else { "CYL_FALSE" }).to_owned(),
        )),
        AstKind::String(v) => {
            let escaped = escape_c_string(v);
            Ok((
                TypesCheck::String,
                format!("cyl_string_from_literal(\"{escaped}\", {})", v.len()),
            ))
        }

        AstKind::UnaryOp {
            op,
            expr,
            expr_type,
        } => {
            let (_, code) = compile_expr(fctx, expr)?;
            let rendered = match op {
                Token::Not => format!("(!({code}))"),
                Token::BitNot => format!("(~({code}))"),
                Token::Minus => format!("(-({code}))"),
                _ => return Err(format!("internal codegen error: bad unary op {op:?}")),
            };
            Ok((expr_type.clone(), rendered))
        }

        AstKind::AsOp { expr, op, src_type } => compile_cast(fctx, expr, op, src_type),

        AstKind::FuncCall { name, args } => compile_expr_call(fctx, name, args, false),

        AstKind::BinaryOp {
            left,
            op,
            right,
            left_type,
            right_type,
        } => compile_binary_op(fctx, left, op, right, left_type, right_type),

        AstKind::ArrayLiteral { values } => compile_array_literal(fctx, values),

        AstKind::ArrayFill { size, value } => compile_array_fill(fctx, size, value),

        AstKind::ArrayGet { name, index } => {
            let ty = fctx.lookup(name)?;
            let elem = match &ty {
                TypesCheck::Array(inner) => (**inner).clone(),
                _ => {
                    return Err(format!(
                        "internal codegen error: ArrayGet on non-array variable '{name}'"
                    ));
                }
            };
            let suffix = array_elem_suffix(&elem);
            let (_, idx_code) = compile_expr(fctx, index)?;
            Ok((
                elem,
                format!("cyl_array_{suffix}_get({}, {idx_code})", c_name(name)),
            ))
        }

        other => Err(format!(
            "internal codegen error: unexpected expression-position node {other:?}"
        )),
    }
}

fn compile_cast(
    fctx: &mut FuncCtx,
    expr: &AstKind,
    op: &Cast,
    src_type: &TypesCheck,
) -> Result<(TypesCheck, String), String> {
    let (_, code) = compile_expr(fctx, expr)?;
    let (dst, rendered) = match (op, src_type) {
        (Cast::String, TypesCheck::Int) => {
            (TypesCheck::String, format!("cyl_int_to_string({code})"))
        }
        (Cast::String, TypesCheck::Float) => {
            (TypesCheck::String, format!("cyl_float_to_string({code})"))
        }
        (Cast::String, TypesCheck::Boolean) => {
            (TypesCheck::String, format!("cyl_bool_to_string({code})"))
        }

        (Cast::Int, TypesCheck::Float) => (TypesCheck::Int, format!("((cyl_int)({code}))")),
        (Cast::Int, TypesCheck::Boolean) => (TypesCheck::Int, format!("((cyl_int)({code}))")),
        (Cast::Int, TypesCheck::String) => {
            (TypesCheck::Int, format!("cyl_string_to_int({code})"))
        }

        (Cast::Float, TypesCheck::Int) => (TypesCheck::Float, format!("((double)({code}))")),
        (Cast::Float, TypesCheck::Boolean) => (TypesCheck::Float, format!("((double)({code}))")),
        (Cast::Float, TypesCheck::String) => {
            (TypesCheck::Float, format!("cyl_string_to_float({code})"))
        }

        (Cast::Boolean, TypesCheck::Int) => {
            (TypesCheck::Boolean, format!("((cyl_bool)(({code}) != 0))"))
        }
        (Cast::Boolean, TypesCheck::Float) => (
            TypesCheck::Boolean,
            format!("((cyl_bool)(({code}) != 0.0))"),
        ),
        (Cast::Boolean, TypesCheck::String) => {
            (TypesCheck::Boolean, format!("cyl_string_to_bool({code})"))
        }

        _ => {
            return Err(format!(
                "internal codegen error: unsupported cast {op:?} from {src_type:?}"
            ));
        }
    };
    Ok((dst, rendered))
}

fn compile_expr_call(
    fctx: &mut FuncCtx,
    name: &str,
    args: &[AstKind],
    in_stmt_position: bool,
) -> Result<(TypesCheck, String), String> {
    match name {
        "input" => return Ok((TypesCheck::String, "cyl_builtin_input()".to_owned())),
        "sin" | "cos" | "sqrt" => {
            let (_, a) = compile_expr(fctx, &args[0])?;
            return Ok((TypesCheck::Float, format!("cyl_builtin_{name}({a})")));
        }
        "shell" => {
            let (_, a) = compile_expr(fctx, &args[0])?;
            return Ok((TypesCheck::Int, format!("cyl_builtin_shell({a})")));
        }
        "unix_time" => {
            return Ok((TypesCheck::Int, "cyl_builtin_unix_time()".to_owned()));
        }
        "sleep" => {
            let (_, a) = compile_expr(fctx, &args[0])?;
            if !in_stmt_position {
                return Err(
                    "internal codegen error: sleep() used in expression position (validator should have rejected this)"
                        .to_owned(),
                );
            }
            return Ok((TypesCheck::Boolean, format!("cyl_builtin_sleep({a})")));
        }
        "len" => {
            let arg_ty = infer_expr_type(fctx, &args[0])?;
            let elem = match arg_ty {
                TypesCheck::Array(inner) => *inner,
                _ => {
                    return Err(
                        "internal codegen error: len() called on a non-array argument".to_owned(),
                    );
                }
            };
            let suffix = array_elem_suffix(&elem);
            let (_, a) = compile_expr(fctx, &args[0])?;
            return Ok((
                TypesCheck::Int,
                format!("((cyl_int)cyl_array_{suffix}_len({a}))"),
            ));
        }
        _ => {}
    }

    let (params, ret) = fctx
        .prog
        .funcs
        .get(name)
        .cloned()
        .ok_or_else(|| format!("internal codegen error: unknown function '{name}'"))?;

    if params.len() != args.len() {
        return Err(format!(
            "internal codegen error: call to '{name}' has {} args, expected {}",
            args.len(),
            params.len()
        ));
    }

    let mut rendered_args = Vec::with_capacity(args.len());
    for arg in args {
        let (_, code) = compile_expr(fctx, arg)?;
        rendered_args.push(code);
    }

    let ret_check = if matches!(ret, ReturnType::Void) {
        if !in_stmt_position {
            return Err(format!(
                "internal codegen error: call to void function '{name}' used in expression position"
            ));
        }
        TypesCheck::Boolean
    } else {
        return_type_to_check(&ret)
    };

    Ok((
        ret_check,
        format!("{}({})", c_func_name(name), rendered_args.join(", ")),
    ))
}

fn infer_expr_type(fctx: &FuncCtx, node: &AstKind) -> Result<TypesCheck, String> {
    match node {
        AstKind::Ident(name) => fctx.lookup(name),

        AstKind::Int(_) => Ok(TypesCheck::Int),
        AstKind::Float(_) => Ok(TypesCheck::Float),
        AstKind::Boolean(_) => Ok(TypesCheck::Boolean),
        AstKind::String(_) => Ok(TypesCheck::String),

        AstKind::BinaryOp {
            op,
            left_type,
            right_type,
            ..
        } => binary_op_result_type(op, left_type, right_type),
        AstKind::UnaryOp { expr_type, .. } => Ok(expr_type.clone()),
        AstKind::AsOp { op, .. } => Ok(match op {
            Cast::String => TypesCheck::String,
            Cast::Int => TypesCheck::Int,
            Cast::Float => TypesCheck::Float,
            Cast::Boolean => TypesCheck::Boolean,
        }),

        AstKind::ArrayLiteral { values } => {
            let first = values
                .first()
                .ok_or_else(|| "internal codegen error: empty array literal".to_owned())?;
            Ok(TypesCheck::Array(Box::new(infer_expr_type(fctx, first)?)))
        }
        AstKind::ArrayFill { value, .. } => {
            Ok(TypesCheck::Array(Box::new(infer_expr_type(fctx, value)?)))
        }
        AstKind::ArrayGet { name, .. } => match fctx.lookup(name)? {
            TypesCheck::Array(inner) => Ok(*inner),
            other => Err(format!(
                "internal codegen error: ArrayGet on non-array type {other:?}"
            )),
        },
        AstKind::FuncCall { name, .. } => {
            let (_, ret) = fctx
                .prog
                .funcs
                .get(name)
                .ok_or_else(|| format!("internal codegen error: unknown function '{name}'"))?;
            Ok(return_type_to_check(ret))
        }
        other => Err(format!(
            "internal codegen error: cannot infer type of {other:?} for len()"
        )),
    }
}

fn compile_array_literal(
    fctx: &mut FuncCtx,
    values: &[AstKind],
) -> Result<(TypesCheck, String), String> {
    if values.is_empty() {
        return Err(
            "internal codegen error: empty array literal (validator should reject this via errors::A48)"
                .to_owned(),
        );
    }
    let elem_ty = infer_expr_type(fctx, &values[0])?;
    let suffix = array_elem_suffix(&elem_ty);

    let tmp = fctx.fresh_tmp("arr");
    let mut parts = vec![format!(
        "({tmp} = cyl_array_{suffix}_new({}))",
        values.len()
    )];
    for (i, v) in values.iter().enumerate() {
        let (_, code) = compile_expr(fctx, v)?;
        parts.push(format!("cyl_array_{suffix}_set({tmp}, {i}, {code})"));
    }
    parts.push(tmp.clone());

    let array_ty = TypesCheck::Array(Box::new(elem_ty));
    fctx.hoisted.push((tmp, array_ty.clone()));

    Ok((array_ty, format!("({})", parts.join(", "))))
}

fn compile_array_fill(
    fctx: &mut FuncCtx,
    size: &AstKind,
    value: &AstKind,
) -> Result<(TypesCheck, String), String> {
    let elem_ty = infer_expr_type(fctx, value)?;
    let suffix = array_elem_suffix(&elem_ty);
    let (_, size_code) = compile_expr(fctx, size)?;
    let (_, value_code) = compile_expr(fctx, value)?;
    let array_ty = TypesCheck::Array(Box::new(elem_ty));
    Ok((
        array_ty,
        format!("cyl_array_{suffix}_fill({size_code}, {value_code})"),
    ))
}

fn binary_op_result_type(
    op: &Token,
    left_type: &TypesCheck,
    right_type: &TypesCheck,
) -> Result<TypesCheck, String> {
    Ok(match op {
        Token::Or | Token::And => TypesCheck::Boolean,

        Token::Plus => match (left_type, right_type) {
            (TypesCheck::Int, TypesCheck::Int) => TypesCheck::Int,
            (TypesCheck::Float, TypesCheck::Float) => TypesCheck::Float,
            (TypesCheck::String, TypesCheck::String)
            | (TypesCheck::String, TypesCheck::Int)
            | (TypesCheck::String, TypesCheck::Float)
            | (TypesCheck::Int, TypesCheck::String)
            | (TypesCheck::Float, TypesCheck::String) => TypesCheck::String,
            _ => {
                return Err(format!(
                    "internal codegen error: bad '+' operand types {left_type:?}/{right_type:?}"
                ));
            }
        },
        Token::Minus => match left_type {
            TypesCheck::Float => TypesCheck::Float,
            _ => TypesCheck::Int,
        },
        Token::Multiply => match (left_type, right_type) {
            (TypesCheck::Int, TypesCheck::Int) => TypesCheck::Int,
            (TypesCheck::Float, TypesCheck::Float) => TypesCheck::Float,
            (TypesCheck::String, TypesCheck::Int) | (TypesCheck::Int, TypesCheck::String) => {
                TypesCheck::String
            }
            _ => {
                return Err(format!(
                    "internal codegen error: bad '*' operand types {left_type:?}/{right_type:?}"
                ));
            }
        },
        Token::Divide | Token::Mod => match left_type {
            TypesCheck::Float => TypesCheck::Float,
            _ => TypesCheck::Int,
        },

        Token::Equal
        | Token::NotEqual
        | Token::Greater
        | Token::Less
        | Token::GreaterEqual
        | Token::LessEqual => TypesCheck::Boolean,

        Token::BitAnd | Token::BitOr | Token::BitXor | Token::BitRight | Token::BitLeft => {
            TypesCheck::Int
        }

        _ => {
            return Err(format!(
                "internal codegen error: unsupported binary op {op:?}"
            ));
        }
    })
}

fn compile_binary_op(
    fctx: &mut FuncCtx,
    left: &AstKind,
    op: &Token,
    right: &AstKind,
    left_type: &TypesCheck,
    right_type: &TypesCheck,
) -> Result<(TypesCheck, String), String> {
    let (_, l) = compile_expr(fctx, left)?;
    let (_, r) = compile_expr(fctx, right)?;

    let result_ty = binary_op_result_type(op, left_type, right_type)?;

    let rendered = match op {
        Token::Or => format!("(({l}) || ({r}))"),
        Token::And => format!("(({l}) && ({r}))"),

        Token::Plus => match (left_type, right_type) {
            (TypesCheck::Int, TypesCheck::Int) => format!("(({l}) + ({r}))"),
            (TypesCheck::Float, TypesCheck::Float) => format!("(({l}) + ({r}))"),
            (TypesCheck::String, TypesCheck::String) => format!("cyl_string_concat({l}, {r})"),
            (TypesCheck::String, TypesCheck::Int) => format!("cyl_string_concat_int({l}, {r})"),
            (TypesCheck::String, TypesCheck::Float) => format!("cyl_string_concat_float({l}, {r})"),
            (TypesCheck::Int, TypesCheck::String) => {
                format!("cyl_string_concat_int_rev({l}, {r})")
            }
            (TypesCheck::Float, TypesCheck::String) => {
                format!("cyl_string_concat_float_rev({l}, {r})")
            }
            _ => unreachable!("binary_op_result_type already validated '+' operand types"),
        },
        Token::Minus => format!("(({l}) - ({r}))"),
        Token::Multiply => match (left_type, right_type) {
            (TypesCheck::Int, TypesCheck::Int) => format!("(({l}) * ({r}))"),
            (TypesCheck::Float, TypesCheck::Float) => format!("(({l}) * ({r}))"),
            (TypesCheck::String, TypesCheck::Int) => format!("cyl_string_repeat({l}, {r})"),
            (TypesCheck::Int, TypesCheck::String) => format!("cyl_string_repeat({r}, {l})"),
            _ => unreachable!("binary_op_result_type already validated '*' operand types"),
        },
        Token::Divide => match left_type {
            TypesCheck::Float => format!("(({l}) / ({r}))"),
            _ => format!("cyl_checked_div({l}, {r})"),
        },
        Token::Mod => match left_type {
            TypesCheck::Float => format!("fmod(({l}), ({r}))"),
            _ => format!("cyl_checked_mod({l}, {r})"),
        },

        Token::Equal => cmp_expr(left_type, "==", &l, &r, "cyl_string_eq"),
        Token::NotEqual => cmp_expr(left_type, "!=", &l, &r, "cyl_string_ne"),
        Token::Greater => cmp_expr(left_type, ">", &l, &r, "cyl_string_gt"),
        Token::Less => cmp_expr(left_type, "<", &l, &r, "cyl_string_lt"),
        Token::GreaterEqual => cmp_expr(left_type, ">=", &l, &r, "cyl_string_ge"),
        Token::LessEqual => cmp_expr(left_type, "<=", &l, &r, "cyl_string_le"),

        Token::BitAnd => format!("(({l}) & ({r}))"),
        Token::BitOr => format!("(({l}) | ({r}))"),
        Token::BitXor => format!("(({l}) ^ ({r}))"),
        Token::BitRight => format!("(({l}) >> ({r}))"),
        Token::BitLeft => format!("(({l}) << ({r}))"),

        _ => unreachable!("binary_op_result_type already rejected unsupported ops"),
    };

    Ok((result_ty, rendered))
}

fn cmp_expr(left_type: &TypesCheck, c_op: &str, l: &str, r: &str, string_fn: &str) -> String {
    match left_type {
        TypesCheck::String => format!("{string_fn}({l}, {r})"),
        _ => format!("(({l}) {c_op} ({r}))"),
    }
}
