// Copyright (c) 2026 Ztry8 (AslanD)
// Licensed under the Apache License, Version 2.0 (the "License");
// You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0

use std::collections::HashMap;
use std::fmt::Write as _;

use crate::{
    lexer::Token,
    parser::{AstKind, AstNode, Cast, ElseBlock},
    types::{ReturnType, TypesCheck},
};

pub fn compile(ast: &[AstNode]) -> Result<String, String> {
    let mut ctx = ProgramCtx::new();

    for node in ast {
        if let AstKind::StructDecl { name, fields } = &node.kind {
            ctx.struct_order.push(name.clone());
            ctx.structs.insert(name.clone(), fields.clone());
        }

        if let AstKind::Func {
            name,
            args,
            return_type,
            ..
        } = &node.kind
        {
            ctx.funcs
                .insert(name.clone(), (args.clone(), return_type.clone()));
        }
    }

    let mut const_decls = String::new();
    let mut const_names: HashMap<String, TypesCheck> = HashMap::new();
    emit_builtin_constants(&mut const_decls, &mut const_names);

    for node in ast {
        if let AstKind::VarDecl {
            name,
            type_,
            value,
            is_const,
        } = &node.kind
        {
            if !*is_const {
                return Err(format!(
                    "internal codegen error: top-level non-const variable '{name}'"
                ));
            }
            emit_top_level_const(&mut const_decls, &mut const_names, name, type_, value)?;
        }
    }

    ctx.const_names = const_names;

    let mut func_decls = String::new();
    let mut func_defs = String::new();
    let struct_decls = emit_struct_decls(&ctx)?;

    for node in ast {
        if let AstKind::Func {
            name,
            body,
            args,
            return_type,
        } = &node.kind
        {
            let sig = render_func_signature(name, args, return_type);
            let _ = writeln!(func_decls, "{sig};");

            let def = compile_function(&ctx, name, args, return_type, body)?;
            func_defs.push_str(&def);
            func_defs.push('\n');
        }
    }

    let mut out = String::new();
    let _ = writeln!(
        out,
        "/* Generated by Cylium c_codegen. Do not edit by hand. */"
    );
    let _ = writeln!(out, "#include \"runtime.h\"");
    let _ = writeln!(out, "#include <stdio.h>");
    let _ = writeln!(out, "#include <stdlib.h>");
    let _ = writeln!(out, "#include <string.h>\n");
    out.push_str(&struct_decls);
    out.push('\n');
    out.push_str(&const_decls);
    out.push('\n');
    out.push_str(&func_decls);
    out.push('\n');
    out.push_str(&func_defs);

    let _ = writeln!(
        out,
        "int main(void)\n{{\n    return (int)cyl_f_main();\n}}\n"
    );

    Ok(out)
}

struct ProgramCtx {
    funcs: HashMap<String, (Vec<(String, TypesCheck)>, ReturnType)>,
    const_names: HashMap<String, TypesCheck>,
    structs: HashMap<String, Vec<(String, TypesCheck)>>,
    struct_order: Vec<String>,
}

impl ProgramCtx {
    fn new() -> Self {
        Self {
            funcs: HashMap::new(),
            const_names: HashMap::new(),
            structs: HashMap::new(),
            struct_order: Vec::new(),
        }
    }

    fn struct_fields(&self, name: &str) -> Result<&[(String, TypesCheck)], String> {
        self.structs
            .get(name)
            .map(Vec::as_slice)
            .ok_or_else(|| format!("internal codegen error: unknown struct '{name}'"))
    }

    fn type_has_heap(&self, t: &TypesCheck) -> bool {
        match t {
            TypesCheck::String | TypesCheck::Array(_) => true,
            TypesCheck::Struct(name) => self
                .structs
                .get(name)
                .is_some_and(|fields| fields.iter().any(|(_, ty)| self.type_has_heap(ty))),
            TypesCheck::Int | TypesCheck::Float | TypesCheck::Boolean => false,
        }
    }
}

struct FuncCtx<'a> {
    prog: &'a ProgramCtx,
    vars: HashMap<String, TypesCheck>,
    hoisted: Vec<(String, TypesCheck)>,
    heap_vars: Vec<(String, TypesCheck)>,
    tmp_counter: usize,
}

fn c_alive_name(name: &str) -> String {
    format!("cyl_alive_{}", c_name(name))
}

impl<'a> FuncCtx<'a> {
    fn new(prog: &'a ProgramCtx) -> Self {
        Self {
            prog,
            vars: HashMap::new(),
            hoisted: Vec::new(),
            heap_vars: Vec::new(),
            tmp_counter: 0,
        }
    }

    fn fresh_tmp(&mut self, prefix: &str) -> String {
        let n = self.tmp_counter;
        self.tmp_counter += 1;
        format!("cyl_tmp_{prefix}_{n}")
    }

    fn declare(&mut self, name: &str, ty: TypesCheck) {
        if !self.vars.contains_key(name) {
            self.hoisted.push((c_name(name), ty.clone()));
            if self.prog.type_has_heap(&ty) {
                self.heap_vars.push((name.to_owned(), ty.clone()));
            }
        }
        self.vars.insert(name.to_owned(), ty);
    }

    fn lookup(&self, name: &str) -> Result<TypesCheck, String> {
        if let Some(t) = self.vars.get(name) {
            return Ok(t.clone());
        }
        if let Some(t) = self.prog.const_names.get(name) {
            return Ok(t.clone());
        }
        Err(format!(
            "internal codegen error: unknown identifier '{name}'"
        ))
    }

    fn is_const(&self, name: &str) -> bool {
        !self.vars.contains_key(name) && self.prog.const_names.contains_key(name)
    }

    fn emit_drop_glue(&self, out: &mut String, pad: &str, skip: Option<&str>) {
        for (name, ty) in &self.heap_vars {
            if skip == Some(name.as_str()) {
                continue;
            }
            let cname = c_name(name);
            let alive = c_alive_name(name);
            let _ = writeln!(
                out,
                "{pad}if ({alive}) {{ {}; {alive} = CYL_FALSE; }}",
                heap_free_expr(self.prog, ty, &cname)
            );
        }
    }
}

fn c_name(name: &str) -> String {
    format!("cyl_v_{name}")
}

fn c_func_name(name: &str) -> String {
    format!("cyl_f_{name}")
}

fn c_const_name(name: &str) -> String {
    format!("cyl_c_{name}")
}

fn c_field_name(name: &str) -> String {
    format!("cyl_f_{name}")
}

fn c_struct_type(name: &str) -> String {
    format!("CylStruct_{name}")
}

fn c_struct_fn(name: &str, suffix: &str) -> String {
    format!("cyl_struct_{name}_{suffix}")
}

fn c_type(t: &TypesCheck) -> String {
    match t {
        TypesCheck::Int => "cyl_int".to_owned(),
        TypesCheck::Float => "double".to_owned(),
        TypesCheck::Boolean => "cyl_bool".to_owned(),
        TypesCheck::String => "CylString".to_owned(),
        TypesCheck::Struct(name) => c_struct_type(name),
        TypesCheck::Array(inner) => match inner.as_ref() {
            TypesCheck::Int => "CylArrayInt".to_owned(),
            TypesCheck::Float => "CylArrayFloat".to_owned(),
            TypesCheck::Boolean => "CylArrayBool".to_owned(),
            TypesCheck::Struct(name) => format!("CylArrayStruct_{name}"),
            other => panic!("unsupported array element type in codegen: {other:?}"),
        },
    }
}

fn c_return_type(t: &ReturnType) -> String {
    match t {
        ReturnType::Void => "void".to_owned(),
        ReturnType::Int => "cyl_int".to_owned(),
        ReturnType::Float => "double".to_owned(),
        ReturnType::Boolean => "cyl_bool".to_owned(),
        ReturnType::String => "CylString".to_owned(),
        ReturnType::Struct(name) => c_struct_type(name),
        ReturnType::Array(inner) => match inner.as_ref() {
            ReturnType::Int => "CylArrayInt".to_owned(),
            ReturnType::Float => "CylArrayFloat".to_owned(),
            ReturnType::Boolean => "CylArrayBool".to_owned(),
            ReturnType::Struct(name) => format!("CylArrayStruct_{name}"),
            other => panic!("unsupported array element type in codegen: {other:?}"),
        },
    }
}

fn return_type_to_check(t: &ReturnType) -> TypesCheck {
    match t {
        ReturnType::Void => unreachable!("Void has no expression-position type"),
        ReturnType::Int => TypesCheck::Int,
        ReturnType::Float => TypesCheck::Float,
        ReturnType::Boolean => TypesCheck::Boolean,
        ReturnType::String => TypesCheck::String,
        ReturnType::Struct(name) => TypesCheck::Struct(name.clone()),
        ReturnType::Array(inner) => TypesCheck::Array(Box::new(return_type_to_check(inner))),
    }
}

fn array_elem_suffix(elem: &TypesCheck) -> String {
    match elem {
        TypesCheck::Int => "int".to_owned(),
        TypesCheck::Float => "float".to_owned(),
        TypesCheck::Boolean => "bool".to_owned(),
        TypesCheck::Struct(name) => format!("struct_{name}"),
        other => panic!("unsupported array element type in codegen: {other:?}"),
    }
}

fn heap_free_expr(ctx: &ProgramCtx, ty: &TypesCheck, expr: &str) -> String {
    match ty {
        TypesCheck::String => format!("cyl_string_free({expr})"),
        TypesCheck::Array(elem) => match elem.as_ref() {
            TypesCheck::Int => format!("cyl_array_int_free({expr})"),
            TypesCheck::Float => format!("cyl_array_float_free({expr})"),
            TypesCheck::Boolean => format!("cyl_array_bool_free({expr})"),
            TypesCheck::Struct(name) => format!("cyl_array_struct_{name}_free({expr})"),
            other => panic!("unsupported array element type in codegen: {other:?}"),
        },
        TypesCheck::Struct(name) if ctx.type_has_heap(ty) => {
            format!("{}({expr})", c_struct_fn(name, "free"))
        }
        TypesCheck::Int | TypesCheck::Float | TypesCheck::Boolean | TypesCheck::Struct(_) => {
            unreachable!("heap_free_fn called on a non-heap type")
        }
    }
}

fn clone_expr(ctx: &ProgramCtx, ty: &TypesCheck, expr: &str) -> String {
    match ty {
        TypesCheck::String => format!("cyl_string_clone({expr})"),
        TypesCheck::Array(elem) => match elem.as_ref() {
            TypesCheck::Int => format!("cyl_array_int_clone({expr})"),
            TypesCheck::Float => format!("cyl_array_float_clone({expr})"),
            TypesCheck::Boolean => format!("cyl_array_bool_clone({expr})"),
            TypesCheck::Struct(name) => format!("cyl_array_struct_{name}_clone({expr})"),
            other => panic!("unsupported array element type in codegen: {other:?}"),
        },
        TypesCheck::Struct(name) if ctx.type_has_heap(ty) => {
            format!("{}({expr})", c_struct_fn(name, "clone"))
        }
        _ => expr.to_owned(),
    }
}

fn emit_struct_decls(ctx: &ProgramCtx) -> Result<String, String> {
    let mut out = String::new();
    emit_array_clone_helpers(&mut out);

    if ctx.struct_order.is_empty() {
        return Ok(out);
    }

    for name in &ctx.struct_order {
        let _ = writeln!(
            out,
            "typedef struct {} {};",
            c_struct_type(name),
            c_struct_type(name)
        );
    }
    out.push('\n');

    for name in &ctx.struct_order {
        emit_struct_array_typedef(&mut out, name);
    }
    out.push('\n');

    for name in &ctx.struct_order {
        let _ = writeln!(out, "struct {} {{", c_struct_type(name));
        for (field, ty) in ctx.struct_fields(name)? {
            let _ = writeln!(out, "    {} {};", c_type(ty), c_field_name(field));
        }
        let _ = writeln!(out, "}};\n");
    }

    for name in &ctx.struct_order {
        let ty = c_struct_type(name);
        let _ = writeln!(out, "static {ty} {}({ty} v);", c_struct_fn(name, "clone"));
        let _ = writeln!(out, "static void {}({ty} v);", c_struct_fn(name, "free"));
        let _ = writeln!(out, "static void {}({ty} v);", c_struct_fn(name, "echo"));
    }
    out.push('\n');

    for name in &ctx.struct_order {
        emit_struct_array_prototypes(&mut out, name);
    }
    out.push('\n');

    for name in &ctx.struct_order {
        emit_struct_clone(ctx, &mut out, name)?;
        emit_struct_free(ctx, &mut out, name)?;
        emit_struct_echo(ctx, &mut out, name)?;
    }

    for name in &ctx.struct_order {
        emit_struct_array_helpers(ctx, &mut out, name)?;
    }

    Ok(out)
}

fn emit_struct_array_typedef(out: &mut String, name: &str) {
    let arr_ty = format!("CylArrayStruct_{name}");
    let elem_ty = c_struct_type(name);
    let _ = writeln!(out, "typedef struct {{");
    let _ = writeln!(out, "    {elem_ty} *data;");
    let _ = writeln!(out, "    size_t len;");
    let _ = writeln!(out, "}} {arr_ty};");
}

fn emit_struct_array_prototypes(out: &mut String, name: &str) {
    let arr_ty = format!("CylArrayStruct_{name}");
    let elem_ty = c_struct_type(name);
    let suffix = format!("struct_{name}");
    let _ = writeln!(out, "static {arr_ty} cyl_array_{suffix}_new(size_t n);");
    let _ = writeln!(
        out,
        "static {arr_ty} cyl_array_{suffix}_fill(cyl_int n, {elem_ty} value);"
    );
    let _ = writeln!(
        out,
        "static {elem_ty} cyl_array_{suffix}_get({arr_ty} a, cyl_int idx);"
    );
    let _ = writeln!(
        out,
        "static void cyl_array_{suffix}_set({arr_ty} a, cyl_int idx, {elem_ty} value);"
    );
    let _ = writeln!(out, "static void cyl_array_{suffix}_free({arr_ty} a);");
    let _ = writeln!(out, "static {arr_ty} cyl_array_{suffix}_clone({arr_ty} a);");
    let _ = writeln!(out, "static size_t cyl_array_{suffix}_len({arr_ty} a);");
}

fn emit_array_clone_helpers(out: &mut String) {
    let specs = [
        ("Int", "int", "cyl_int"),
        ("Float", "float", "double"),
        ("Bool", "bool", "cyl_bool"),
    ];

    for (type_suffix, fn_suffix, elem_ty) in specs {
        let _ = writeln!(
            out,
            "static CylArray{type_suffix} cyl_array_{fn_suffix}_clone(CylArray{type_suffix} a)\n{{"
        );
        let _ = writeln!(out, "    CylArray{type_suffix} out;");
        let _ = writeln!(out, "    size_t i;");
        let _ = writeln!(out, "    out = cyl_array_{fn_suffix}_new(a.len);");
        let _ = writeln!(out, "    for (i = 0; i < a.len; i++) {{");
        let _ = writeln!(out, "        out.data[i] = ({elem_ty})a.data[i];");
        let _ = writeln!(out, "    }}");
        let _ = writeln!(out, "    return out;");
        let _ = writeln!(out, "}}\n");
    }
}

fn emit_struct_clone(ctx: &ProgramCtx, out: &mut String, name: &str) -> Result<(), String> {
    let ty = c_struct_type(name);
    let _ = writeln!(
        out,
        "static {ty} {}({ty} v)\n{{",
        c_struct_fn(name, "clone")
    );
    let _ = writeln!(out, "    {ty} out;");
    for (field, field_ty) in ctx.struct_fields(name)? {
        let src = format!("v.{}", c_field_name(field));
        let dst = format!("out.{}", c_field_name(field));
        let _ = writeln!(out, "    {dst} = {};", clone_expr(ctx, field_ty, &src));
    }
    let _ = writeln!(out, "    return out;");
    let _ = writeln!(out, "}}\n");
    Ok(())
}

fn emit_struct_free(ctx: &ProgramCtx, out: &mut String, name: &str) -> Result<(), String> {
    let ty = c_struct_type(name);
    let _ = writeln!(out, "static void {}({ty} v)\n{{", c_struct_fn(name, "free"));
    for (field, field_ty) in ctx.struct_fields(name)? {
        if ctx.type_has_heap(field_ty) {
            let expr = format!("v.{}", c_field_name(field));
            let _ = writeln!(out, "    {};", heap_free_expr(ctx, field_ty, &expr));
        }
    }
    let _ = writeln!(out, "}}\n");
    Ok(())
}

fn emit_struct_echo(ctx: &ProgramCtx, out: &mut String, name: &str) -> Result<(), String> {
    let ty = c_struct_type(name);
    let fields = ctx.struct_fields(name)?;
    let _ = writeln!(out, "static void {}({ty} v)\n{{", c_struct_fn(name, "echo"));
    let _ = writeln!(out, "    printf(\"{name}(\");");
    for (idx, (field, field_ty)) in fields.iter().enumerate() {
        let prefix = if idx == 0 {
            format!("{field}: ")
        } else {
            format!(", {field}: ")
        };
        let _ = writeln!(out, "    printf(\"{}\");", escape_c_string(&prefix));
        emit_echo_value(ctx, out, field_ty, &format!("v.{}", c_field_name(field)))?;
    }
    let _ = writeln!(out, "    printf(\")\");");
    let _ = writeln!(out, "}}\n");
    Ok(())
}

fn emit_struct_array_helpers(ctx: &ProgramCtx, out: &mut String, name: &str) -> Result<(), String> {
    let arr_ty = format!("CylArrayStruct_{name}");
    let elem_ty = TypesCheck::Struct(name.to_owned());
    let elem_c_ty = c_struct_type(name);
    let suffix = format!("struct_{name}");

    let _ = writeln!(out, "static {arr_ty} cyl_array_{suffix}_new(size_t n)\n{{");
    let _ = writeln!(out, "    {arr_ty} a;");
    let _ = writeln!(out, "    a.len = n;");
    let _ = writeln!(
        out,
        "    a.data = ({elem_c_ty} *)malloc(n * sizeof({elem_c_ty}));"
    );
    let _ = writeln!(out, "    if (a.data == NULL && n != 0) {{");
    let _ = writeln!(out, "        cyl_panic(\"out of memory\");");
    let _ = writeln!(out, "    }}");
    let _ = writeln!(out, "    memset(a.data, 0, n * sizeof({elem_c_ty}));");
    let _ = writeln!(out, "    return a;");
    let _ = writeln!(out, "}}\n");

    let _ = writeln!(
        out,
        "static {arr_ty} cyl_array_{suffix}_fill(cyl_int n, {elem_c_ty} value)\n{{"
    );
    let _ = writeln!(out, "    {arr_ty} a;");
    let _ = writeln!(out, "    size_t i;");
    let _ = writeln!(out, "    a = cyl_array_{suffix}_new((size_t)n);");
    let _ = writeln!(out, "    for (i = 0; i < a.len; i++) {{");
    let _ = writeln!(
        out,
        "        a.data[i] = {};",
        clone_expr(ctx, &elem_ty, "value")
    );
    let _ = writeln!(out, "    }}");
    if ctx.type_has_heap(&elem_ty) {
        let _ = writeln!(out, "    {};", heap_free_expr(ctx, &elem_ty, "value"));
    }
    let _ = writeln!(out, "    return a;");
    let _ = writeln!(out, "}}\n");

    let _ = writeln!(
        out,
        "static {elem_c_ty} cyl_array_{suffix}_get({arr_ty} a, cyl_int idx)\n{{"
    );
    let _ = writeln!(out, "    if (idx < 0 || (size_t)idx >= a.len) {{");
    let _ = writeln!(out, "        cyl_panic(\"array index out of bounds\");");
    let _ = writeln!(out, "    }}");
    let _ = writeln!(
        out,
        "    return {};",
        clone_expr(ctx, &elem_ty, "a.data[idx]")
    );
    let _ = writeln!(out, "}}\n");

    let _ = writeln!(
        out,
        "static void cyl_array_{suffix}_set({arr_ty} a, cyl_int idx, {elem_c_ty} value)\n{{"
    );
    let _ = writeln!(out, "    if (idx < 0 || (size_t)idx >= a.len) {{");
    let _ = writeln!(out, "        cyl_panic(\"array index out of bounds\");");
    let _ = writeln!(out, "    }}");
    if ctx.type_has_heap(&elem_ty) {
        let _ = writeln!(out, "    {};", heap_free_expr(ctx, &elem_ty, "a.data[idx]"));
    }
    let _ = writeln!(out, "    a.data[idx] = value;");
    let _ = writeln!(out, "}}\n");

    let _ = writeln!(out, "static void cyl_array_{suffix}_free({arr_ty} a)\n{{");
    let _ = writeln!(out, "    size_t i;");
    if ctx.type_has_heap(&elem_ty) {
        let _ = writeln!(out, "    for (i = 0; i < a.len; i++) {{");
        let _ = writeln!(
            out,
            "        {};",
            heap_free_expr(ctx, &elem_ty, "a.data[i]")
        );
        let _ = writeln!(out, "    }}");
    } else {
        let _ = writeln!(out, "    (void)i;");
    }
    let _ = writeln!(out, "    free(a.data);");
    let _ = writeln!(out, "}}\n");

    let _ = writeln!(
        out,
        "static {arr_ty} cyl_array_{suffix}_clone({arr_ty} a)\n{{"
    );
    let _ = writeln!(out, "    {arr_ty} out;");
    let _ = writeln!(out, "    size_t i;");
    let _ = writeln!(out, "    out = cyl_array_{suffix}_new(a.len);");
    let _ = writeln!(out, "    for (i = 0; i < a.len; i++) {{");
    let _ = writeln!(
        out,
        "        out.data[i] = {};",
        clone_expr(ctx, &elem_ty, "a.data[i]")
    );
    let _ = writeln!(out, "    }}");
    let _ = writeln!(out, "    return out;");
    let _ = writeln!(out, "}}\n");

    let _ = writeln!(out, "static size_t cyl_array_{suffix}_len({arr_ty} a)");
    let _ = writeln!(out, "{{");
    let _ = writeln!(out, "    return a.len;");
    let _ = writeln!(out, "}}\n");

    Ok(())
}

fn emit_echo_value(
    ctx: &ProgramCtx,
    out: &mut String,
    ty: &TypesCheck,
    expr: &str,
) -> Result<(), String> {
    match ty {
        TypesCheck::Int => {
            let _ = writeln!(out, "    printf(\"%ld\", {expr});");
        }
        TypesCheck::Float => {
            let _ = writeln!(out, "    printf(\"%g\", {expr});");
        }
        TypesCheck::Boolean => {
            let _ = writeln!(out, "    printf(\"%s\", {expr} ? \"true\" : \"false\");");
        }
        TypesCheck::String => {
            let _ = writeln!(out, "    printf(\"%s\", {expr}.data);");
        }
        TypesCheck::Struct(name) => {
            let _ = writeln!(out, "    {}({expr});", c_struct_fn(name, "echo"));
        }
        TypesCheck::Array(_) => {
            let _ = writeln!(out, "    printf(\"<array>\");");
        }
    }
    let _ = ctx;
    Ok(())
}

fn emit_builtin_constants(out: &mut String, names: &mut HashMap<String, TypesCheck>) {
    let _ = writeln!(
        out,
        "static const double {} = 3.14159265358979323846;",
        c_const_name("PI")
    );
    let _ = writeln!(
        out,
        "static const double {} = 2.71828182845904523536;",
        c_const_name("E")
    );
    names.insert("PI".to_owned(), TypesCheck::Float);
    names.insert("E".to_owned(), TypesCheck::Float);

    let platform_consts = [
        ("IS_LINUX", "__linux__"),
        ("IS_MACOS", "__APPLE__"),
        ("IS_WINDOWS", "_WIN32"),
        ("IS_X86_64", "__x86_64__"),
        ("IS_ARM64", "__aarch64__"),
    ];
    for (name, cfg_macro) in platform_consts {
        let _ = writeln!(out, "#if defined({cfg_macro})");
        let _ = writeln!(
            out,
            "static const cyl_bool {} = CYL_TRUE;",
            c_const_name(name)
        );
        let _ = writeln!(out, "#else");
        let _ = writeln!(
            out,
            "static const cyl_bool {} = CYL_FALSE;",
            c_const_name(name)
        );
        let _ = writeln!(out, "#endif");
        names.insert(name.to_owned(), TypesCheck::Boolean);
    }
}

fn emit_top_level_const(
    out: &mut String,
    names: &mut HashMap<String, TypesCheck>,
    name: &str,
    type_: &TypesCheck,
    value: &AstKind,
) -> Result<(), String> {
    match (type_, value) {
        (TypesCheck::Int, AstKind::Int(v)) => {
            let _ = writeln!(out, "static const cyl_int {} = {v}L;", c_const_name(name));
        }
        (TypesCheck::Float, AstKind::Float(v)) => {
            let _ = writeln!(
                out,
                "static const double {} = {};",
                c_const_name(name),
                format_c_float(*v)
            );
        }
        (TypesCheck::Boolean, AstKind::Boolean(v)) => {
            let _ = writeln!(
                out,
                "static const cyl_bool {} = {};",
                c_const_name(name),
                if *v { "CYL_TRUE" } else { "CYL_FALSE" }
            );
        }
        (TypesCheck::String, AstKind::String(v)) => {
            let escaped = escape_c_string(v);
            let _ = writeln!(
                out,
                "static char {}_buf[] = \"{escaped}\";",
                c_const_name(name)
            );
            let _ = writeln!(
                out,
                "static const CylString {} = {{ {}_buf, {} }};",
                c_const_name(name),
                c_const_name(name),
                v.len()
            );
        }
        _ => {
            return Err(format!(
                "codegen limitation: top-level const '{name}' must be a literal of its declared type"
            ));
        }
    }

    names.insert(name.to_owned(), type_.clone());
    Ok(())
}

fn escape_c_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for b in s.bytes() {
        match b {
            b'\\' => out.push_str("\\\\"),
            b'"' => out.push_str("\\\""),
            b'\n' => out.push_str("\\n"),
            b'\r' => out.push_str("\\r"),
            b'\t' => out.push_str("\\t"),
            0x20..=0x7e => out.push(b as char),
            _ => {
                let _ = write!(out, "\\x{b:02x}\"\"");
            }
        }
    }
    out
}

fn format_c_float(v: f64) -> String {
    if v.is_infinite() {
        return if v > 0.0 {
            "(1.0/0.0)".to_owned()
        } else {
            "(-1.0/0.0)".to_owned()
        };
    }
    if v.is_nan() {
        return "(0.0/0.0)".to_owned();
    }
    let s = format!("{v:?}");
    if s.contains('.') || s.contains('e') || s.contains("inf") || s.contains("NaN") {
        s
    } else {
        format!("{s}.0")
    }
}

fn render_func_signature(
    name: &str,
    args: &[(String, TypesCheck)],
    return_type: &ReturnType,
) -> String {
    let params = if args.is_empty() {
        "void".to_owned()
    } else {
        args.iter()
            .map(|(n, t)| format!("{} {}", c_type(t), c_name(n)))
            .collect::<Vec<_>>()
            .join(", ")
    };
    format!(
        "{} {}({})",
        c_return_type(return_type),
        c_func_name(name),
        params
    )
}

fn compile_function(
    prog: &ProgramCtx,
    name: &str,
    args: &[(String, TypesCheck)],
    return_type: &ReturnType,
    body: &[AstNode],
) -> Result<String, String> {
    let mut fctx = FuncCtx::new(prog);

    for (pname, ptype) in args {
        fctx.vars.insert(pname.clone(), ptype.clone());
        if prog.type_has_heap(ptype) {
            fctx.heap_vars.push((pname.clone(), ptype.clone()));
        }
    }

    let mut body_code = String::new();
    for node in body {
        compile_stmt(&mut fctx, &mut body_code, &node.kind, 1)?;
    }

    let mut out = String::new();
    let sig = render_func_signature(name, args, return_type);
    let _ = writeln!(out, "{sig}\n{{");

    for (cname, ty) in &fctx.hoisted {
        let _ = writeln!(out, "    {} {};", c_type(ty), cname);
    }
    for (hvar_name, _) in &fctx.heap_vars {
        let _ = writeln!(out, "    cyl_bool {};", c_alive_name(hvar_name));
    }
    if !fctx.hoisted.is_empty() || !fctx.heap_vars.is_empty() {
        out.push('\n');
    }

    for (pname, ptype) in args {
        if prog.type_has_heap(ptype) {
            let _ = writeln!(out, "    {} = CYL_TRUE;", c_alive_name(pname));
        }
    }
    for (lname, _) in &fctx.heap_vars {
        if args.iter().any(|(pname, _)| pname == lname) {
            continue;
        }
        let _ = writeln!(out, "    {} = CYL_FALSE;", c_alive_name(lname));
    }
    out.push('\n');

    out.push_str(&body_code);

    if matches!(return_type, ReturnType::Void) {
        fctx.emit_drop_glue(&mut out, "    ", None);
    }

    if !matches!(return_type, ReturnType::Void) {
        let _ = writeln!(
            out,
            "    cyl_panic(\"unreachable: function fell through without returning\");"
        );
        let _ = writeln!(out, "    {{");
        let _ = writeln!(out, "        {} cyl_dummy_ret;", c_return_type(return_type));
        let _ = writeln!(
            out,
            "        memset(&cyl_dummy_ret, 0, sizeof(cyl_dummy_ret));"
        );
        let _ = writeln!(out, "        return cyl_dummy_ret;");
        let _ = writeln!(out, "    }}");
    }

    let _ = writeln!(out, "}}");
    Ok(out)
}

fn ind(level: usize) -> String {
    "    ".repeat(level)
}

fn compile_return_value(
    fctx: &mut FuncCtx,
    out: &mut String,
    pad: &str,
    expr: &AstKind,
) -> Result<(), String> {
    if let AstKind::Ident(name) = expr {
        let ty = fctx.lookup(name)?;
        if matches!(ty, TypesCheck::Array(_)) {
            fctx.emit_drop_glue(out, pad, Some(name));
            let _ = writeln!(out, "{pad}return {};", c_name(name));
            return Ok(());
        }
    }

    let (ty, code) = compile_expr(fctx, expr)?;

    if fctx.prog.type_has_heap(&ty) {
        let tmp = fctx.fresh_tmp("ret");
        fctx.hoisted.push((tmp.clone(), ty.clone()));
        let _ = writeln!(out, "{pad}{tmp} = {code};");
        fctx.emit_drop_glue(out, pad, None);
        let _ = writeln!(out, "{pad}return {tmp};");
        return Ok(());
    }

    fctx.emit_drop_glue(out, pad, None);
    let _ = writeln!(out, "{pad}return {code};");
    Ok(())
}

fn compile_stmt(
    fctx: &mut FuncCtx,
    out: &mut String,
    node: &AstKind,
    level: usize,
) -> Result<(), String> {
    let pad = ind(level);
    match node {
        AstKind::Echo(expr) => {
            let (ty, code) = compile_expr(fctx, expr)?;
            match ty {
                TypesCheck::Int => {
                    let _ = writeln!(out, "{pad}cyl_echo_int({code});");
                }
                TypesCheck::Float => {
                    let _ = writeln!(out, "{pad}cyl_echo_float({code});");
                }
                TypesCheck::Boolean => {
                    let _ = writeln!(out, "{pad}cyl_echo_bool({code});");
                }
                TypesCheck::String => {
                    let _ = writeln!(out, "{pad}cyl_echo_and_free_string({code});");
                }
                TypesCheck::Struct(name) => {
                    let struct_ty = TypesCheck::Struct(name.clone());
                    if fctx.prog.type_has_heap(&struct_ty) {
                        let tmp = fctx.fresh_tmp("echo");
                        fctx.hoisted.push((tmp.clone(), struct_ty.clone()));
                        let _ = writeln!(out, "{pad}{tmp} = {code};");
                        let _ = writeln!(out, "{pad}{}({tmp});", c_struct_fn(&name, "echo"));
                        let _ = writeln!(out, "{pad}printf(\"\\n\");");
                        let _ =
                            writeln!(out, "{pad}{};", heap_free_expr(fctx.prog, &struct_ty, &tmp));
                    } else {
                        let _ = writeln!(out, "{pad}{}({code});", c_struct_fn(&name, "echo"));
                        let _ = writeln!(out, "{pad}printf(\"\\n\");");
                    }
                }
                TypesCheck::Array(_) => {
                    return Err(
                        "codegen error: echo of an array is not supported by the runtime"
                            .to_owned(),
                    );
                }
            }
        }
        AstKind::Delete(name) => {
            let ty = fctx.lookup(name)?;
            if fctx.prog.type_has_heap(&ty) {
                let _ = writeln!(
                    out,
                    "{pad}{};",
                    heap_free_expr(fctx.prog, &ty, &c_name(name))
                );
                let _ = writeln!(out, "{pad}{} = CYL_FALSE;", c_alive_name(name));
            }
        }
        AstKind::Exit(code) => {
            let _ = writeln!(out, "{pad}exit({code});");
        }
        AstKind::VarDecl {
            name, type_, value, ..
        } => {
            fctx.declare(name, type_.clone());
            let code = compile_value_for_type(fctx, type_, value)?;
            let _ = writeln!(out, "{pad}{} = {code};", c_name(name));
            if fctx.prog.type_has_heap(type_) {
                let _ = writeln!(out, "{pad}{} = CYL_TRUE;", c_alive_name(name));
            }
        }
        AstKind::ArraySet {
            name,
            index,
            op,
            expr,
            elem_type,
        } => {
            compile_array_set(fctx, out, &pad, name, index, op, expr, elem_type)?;
        }
        AstKind::StructSet {
            name,
            member,
            op,
            expr,
            elem_type,
        } => {
            compile_struct_set(fctx, out, &pad, name, member, op, expr, elem_type)?;
        }
        AstKind::Return(None) => {
            fctx.emit_drop_glue(out, &pad, None);
            let _ = writeln!(out, "{pad}return;");
        }
        AstKind::Return(Some(expr)) => {
            compile_return_value(fctx, out, &pad, expr)?;
        }
        AstKind::FuncCall { name, args } => {
            compile_call_stmt(fctx, out, &pad, name, args)?;
        }
        AstKind::Assign {
            name,
            op,
            expr,
            var_type,
        } => {
            compile_assign(fctx, out, &pad, name, op, expr, var_type)?;
        }
        AstKind::Condition { expr, yes, no } => {
            let (_, cond_code) = compile_expr(fctx, expr)?;
            let _ = writeln!(out, "{pad}if ({cond_code}) {{");
            for n in yes {
                compile_stmt(fctx, out, &n.kind, level + 1)?;
            }
            match no {
                None => {
                    let _ = writeln!(out, "{pad}}}");
                }
                Some(ElseBlock::Else(else_body)) => {
                    let _ = writeln!(out, "{pad}}} else {{");
                    for n in else_body {
                        compile_stmt(fctx, out, &n.kind, level + 1)?;
                    }
                    let _ = writeln!(out, "{pad}}}");
                }
                Some(ElseBlock::ElseIf(elseif_node)) => {
                    let _ = writeln!(out, "{pad}}} else {{");
                    compile_stmt(fctx, out, &elseif_node.kind, level + 1)?;
                    let _ = writeln!(out, "{pad}}}");
                }
            }
        }
        AstKind::While { expr, body } => {
            let (_, cond_code) = compile_expr(fctx, expr)?;
            let _ = writeln!(out, "{pad}while ({cond_code}) {{");
            for n in body {
                compile_stmt(fctx, out, &n.kind, level + 1)?;
            }
            let _ = writeln!(out, "{pad}}}");
        }
        AstKind::For {
            var_name,
            start,
            end,
            step,
            body,
        } => {
            compile_for(fctx, out, &pad, level, var_name, start, end, step, body)?;
        }
        other => {
            return Err(format!(
                "internal codegen error: unexpected statement-position node {other:?}"
            ));
        }
    }
    Ok(())
}

fn compile_call_stmt(
    fctx: &mut FuncCtx,
    out: &mut String,
    pad: &str,
    name: &str,
    args: &[AstKind],
) -> Result<(), String> {
    let (ty, code) = compile_expr_call(fctx, name, args, true)?;
    if fctx.prog.type_has_heap(&ty) {
        let _ = writeln!(out, "{pad}{};", heap_free_expr(fctx.prog, &ty, &code));
    } else {
        let _ = writeln!(out, "{pad}{code};");
    }
    Ok(())
}

fn simple_compound_op(op: &Token) -> Option<&'static str> {
    match op {
        Token::PlusAssign => Some("+="),
        Token::MinusAssign => Some("-="),
        Token::MultiplyAssign => Some("*="),
        Token::DivideAssign => Some("/="),
        Token::ModAssign => Some("%="),
        Token::BitAndAssign => Some("&="),
        Token::BitOrAssign => Some("|="),
        Token::BitXorAssign => Some("^="),
        Token::BitRightAssign => Some(">>="),
        Token::BitLeftAssign => Some("<<="),
        _ => None,
    }
}

fn compile_assign(
    fctx: &mut FuncCtx,
    out: &mut String,
    pad: &str,
    name: &str,
    op: &Token,
    expr: &AstKind,
    var_type: &TypesCheck,
) -> Result<(), String> {
    if fctx.is_const(name) {
        return Err(format!(
            "internal codegen error: assignment to const '{name}' should have been rejected by the validator"
        ));
    }

    let cname = c_name(name);

    if *op == Token::Assign {
        let code = compile_value_for_type(fctx, var_type, expr)?;
        if fctx.prog.type_has_heap(var_type) {
            let tmp = fctx.fresh_tmp("assign");
            fctx.hoisted.push((tmp.clone(), var_type.clone()));
            let _ = writeln!(out, "{pad}{tmp} = {code};");
            let _ = writeln!(out, "{pad}{};", heap_free_expr(fctx.prog, var_type, &cname));
            let _ = writeln!(out, "{pad}{cname} = {tmp};");
        } else {
            let _ = writeln!(out, "{pad}{cname} = {code};");
        }
        return Ok(());
    }

    match var_type {
        TypesCheck::Int | TypesCheck::Float => {
            let c_op = simple_compound_op(op).ok_or_else(|| {
                format!("internal codegen error: unsupported compound op {op:?} for numeric type")
            })?;
            let (_, code) = compile_expr(fctx, expr)?;
            let _ = writeln!(out, "{pad}{cname} {c_op} {code};");
        }
        TypesCheck::String => {
            let (_, code) = compile_expr(fctx, expr)?;
            let new_val = match op {
                Token::PlusAssign => format!("cyl_string_concat({cname}, {code})"),
                Token::MultiplyAssign => format!("cyl_string_repeat({cname}, {code})"),
                _ => {
                    return Err(format!(
                        "internal codegen error: unsupported compound op {op:?} for string type"
                    ));
                }
            };
            let _ = writeln!(out, "{pad}{cname} = {new_val};");
        }
        TypesCheck::Array(_) | TypesCheck::Boolean | TypesCheck::Struct(_) => {
            return Err(format!(
                "internal codegen error: compound assignment on {var_type:?} should have been rejected by the validator"
            ));
        }
    }

    Ok(())
}

fn compile_struct_set(
    fctx: &mut FuncCtx,
    out: &mut String,
    pad: &str,
    name: &str,
    member: &str,
    op: &Token,
    expr: &AstKind,
    elem_type: &TypesCheck,
) -> Result<(), String> {
    let target = format!("{}.{}", c_name(name), c_field_name(member));

    if *op == Token::Assign {
        let code = compile_value_for_type(fctx, elem_type, expr)?;
        if fctx.prog.type_has_heap(elem_type) {
            let tmp = fctx.fresh_tmp("field");
            fctx.hoisted.push((tmp.clone(), elem_type.clone()));
            let _ = writeln!(out, "{pad}{tmp} = {code};");
            let _ = writeln!(
                out,
                "{pad}{};",
                heap_free_expr(fctx.prog, elem_type, &target)
            );
            let _ = writeln!(out, "{pad}{target} = {tmp};");
        } else {
            let _ = writeln!(out, "{pad}{target} = {code};");
        }
        return Ok(());
    }

    match elem_type {
        TypesCheck::Int | TypesCheck::Float => {
            let c_op = simple_compound_op(op).ok_or_else(|| {
                format!("internal codegen error: unsupported compound op {op:?} for struct field")
            })?;
            let (_, code) = compile_expr(fctx, expr)?;
            let _ = writeln!(out, "{pad}{target} {c_op} {code};");
        }
        TypesCheck::String => {
            let (_, code) = compile_expr(fctx, expr)?;
            let new_val = match op {
                Token::PlusAssign => format!("cyl_string_concat({target}, {code})"),
                Token::MultiplyAssign => format!("cyl_string_repeat({target}, {code})"),
                _ => {
                    return Err(format!(
                        "internal codegen error: unsupported compound op {op:?} for string field"
                    ));
                }
            };
            let _ = writeln!(out, "{pad}{target} = {new_val};");
        }
        TypesCheck::Array(_) | TypesCheck::Boolean | TypesCheck::Struct(_) => {
            return Err(format!(
                "internal codegen error: compound assignment on field type {elem_type:?} should have been rejected by the validator"
            ));
        }
    }

    Ok(())
}

fn compile_value_for_type(
    fctx: &mut FuncCtx,
    expected: &TypesCheck,
    value: &AstKind,
) -> Result<String, String> {
    match (expected, value) {
        (TypesCheck::Struct(name), AstKind::StructShortLiteral { fields }) => {
            compile_struct_literal(fctx, name, fields, None)
        }
        (TypesCheck::Struct(name), AstKind::StructLongLiteral { fields }) => {
            compile_struct_literal(fctx, name, &[], Some(fields))
        }
        _ => {
            let (_, code) = compile_expr(fctx, value)?;
            Ok(code)
        }
    }
}

fn compile_struct_literal(
    fctx: &mut FuncCtx,
    struct_name: &str,
    short_fields: &[AstKind],
    long_fields: Option<&[(String, Box<AstKind>)]>,
) -> Result<String, String> {
    let fields = fctx.prog.struct_fields(struct_name)?.to_vec();
    let tmp = fctx.fresh_tmp("struct");
    fctx.hoisted
        .push((tmp.clone(), TypesCheck::Struct(struct_name.to_owned())));

    let mut parts = Vec::new();
    for (idx, (field_name, field_ty)) in fields.iter().enumerate() {
        let expr = if let Some(long_fields) = long_fields {
            long_fields
                .iter()
                .find(|(name, _)| name == field_name)
                .map(|(_, value)| value.as_ref())
                .ok_or_else(|| {
                    format!(
                        "internal codegen error: missing field '{field_name}' in struct literal"
                    )
                })?
        } else {
            short_fields.get(idx).ok_or_else(|| {
                "internal codegen error: short struct literal too short".to_owned()
            })?
        };
        let value = compile_value_for_type(fctx, field_ty, expr)?;
        parts.push(format!("({tmp}.{} = {value})", c_field_name(field_name)));
    }
    parts.push(tmp);

    Ok(format!("({})", parts.join(", ")))
}

fn compile_array_set(
    fctx: &mut FuncCtx,
    out: &mut String,
    pad: &str,
    name: &str,
    index: &AstKind,
    op: &Token,
    expr: &AstKind,
    elem_type: &TypesCheck,
) -> Result<(), String> {
    let cname = c_name(name);
    let suffix = array_elem_suffix(elem_type);
    let get_fn = format!("cyl_array_{suffix}_get");
    let set_fn = format!("cyl_array_{suffix}_set");

    if *op == Token::Assign {
        let (_, val_code) = compile_expr(fctx, expr)?;
        let (_, idx_code) = compile_expr(fctx, index)?;
        let _ = writeln!(out, "{pad}{set_fn}({cname}, {idx_code}, {val_code});");
        return Ok(());
    }

    let (_, idx_code_read) = compile_expr(fctx, index)?;
    let current = format!("{get_fn}({cname}, {idx_code_read})");
    let (_, rhs) = compile_expr(fctx, expr)?;

    let new_val = match elem_type {
        TypesCheck::Float => match op {
            Token::PlusAssign => format!("({current} + {rhs})"),
            Token::MinusAssign => format!("({current} - {rhs})"),
            Token::MultiplyAssign => format!("({current} * {rhs})"),
            Token::DivideAssign => format!("({current} / {rhs})"),
            _ => {
                return Err(format!(
                    "internal codegen error: unsupported compound array op {op:?} for float element"
                ));
            }
        },
        TypesCheck::String => match op {
            Token::PlusAssign => format!("cyl_string_concat({current}, {rhs})"),
            _ => {
                return Err(format!(
                    "internal codegen error: unsupported compound array op {op:?} for string element"
                ));
            }
        },
        TypesCheck::Int => {
            let c_op = simple_compound_op(op).ok_or_else(|| {
                format!("internal codegen error: unsupported compound array op {op:?}")
            })?;
            let bin_op = &c_op[..c_op.len() - 1];
            format!("({current} {bin_op} {rhs})")
        }
        TypesCheck::Boolean | TypesCheck::Array(_) | TypesCheck::Struct(_) => {
            return Err(format!(
                "internal codegen error: compound array assignment on element type {elem_type:?} should have been rejected by the validator"
            ));
        }
    };

    let (_, idx_code_write) = compile_expr(fctx, index)?;
    let _ = writeln!(out, "{pad}{set_fn}({cname}, {idx_code_write}, {new_val});");
    Ok(())
}

fn compile_for(
    fctx: &mut FuncCtx,
    out: &mut String,
    pad: &str,
    level: usize,
    var_name: &str,
    start: &AstKind,
    end: &AstKind,
    step: &Option<AstKind>,
    body: &[AstNode],
) -> Result<(), String> {
    fctx.declare(var_name, TypesCheck::Int);
    let (_, start_code) = compile_expr(fctx, start)?;
    let _ = writeln!(out, "{pad}{} = {start_code};", c_name(var_name));

    let end_var = hidden_for_var("fe", var_name);
    fctx.declare(&end_var, TypesCheck::Int);
    let (_, end_code) = compile_expr(fctx, end)?;
    let _ = writeln!(out, "{pad}{} = {end_code};", c_name(&end_var));

    let step_var = match step {
        Some(step_expr) => {
            let sv = hidden_for_var("fs", var_name);
            fctx.declare(&sv, TypesCheck::Int);
            let (_, step_code) = compile_expr(fctx, step_expr)?;
            let _ = writeln!(out, "{pad}{} = {step_code};", c_name(&sv));
            Some(sv)
        }
        None => None,
    };

    let _ = writeln!(
        out,
        "{pad}while ({} <= {}) {{",
        c_name(var_name),
        c_name(&end_var)
    );
    for n in body {
        compile_stmt(fctx, out, &n.kind, level + 1)?;
    }
    let inner_pad = ind(level + 1);
    match &step_var {
        Some(sv) => {
            let _ = writeln!(out, "{inner_pad}{} += {};", c_name(var_name), c_name(sv));
        }
        None => {
            let _ = writeln!(out, "{inner_pad}{} += 1;", c_name(var_name));
        }
    }
    let _ = writeln!(out, "{pad}}}");
    Ok(())
}

fn hidden_for_var(tag: &str, var_name: &str) -> String {
    format!("__hidden_for_{tag}_{var_name}")
}

fn compile_expr(fctx: &mut FuncCtx, node: &AstKind) -> Result<(TypesCheck, String), String> {
    match node {
        AstKind::Ident(name) => {
            let ty = fctx.lookup(name)?;
            let cname = if fctx.is_const(name) {
                c_const_name(name)
            } else {
                c_name(name)
            };
            match &ty {
                TypesCheck::String => Ok((ty.clone(), clone_expr(fctx.prog, &ty, &cname))),
                TypesCheck::Struct(_) if fctx.prog.type_has_heap(&ty) => {
                    Ok((ty.clone(), clone_expr(fctx.prog, &ty, &cname)))
                }
                TypesCheck::Array(_) => Ok((ty.clone(), clone_expr(fctx.prog, &ty, &cname))),
                _ => Ok((ty.clone(), cname)),
            }
        }

        AstKind::Int(v) => Ok((TypesCheck::Int, format!("{v}L"))),
        AstKind::Float(v) => Ok((TypesCheck::Float, format_c_float(*v))),
        AstKind::Boolean(v) => Ok((
            TypesCheck::Boolean,
            (if *v { "CYL_TRUE" } else { "CYL_FALSE" }).to_owned(),
        )),
        AstKind::String(v) => {
            let escaped = escape_c_string(v);
            Ok((
                TypesCheck::String,
                format!("cyl_string_from_literal(\"{escaped}\", {})", v.len()),
            ))
        }

        AstKind::UnaryOp {
            op,
            expr,
            expr_type,
        } => {
            let (_, code) = compile_expr(fctx, expr)?;
            let rendered = match op {
                Token::Not => format!("(!({code}))"),
                Token::BitNot => format!("(~({code}))"),
                Token::Minus => format!("(-({code}))"),
                _ => return Err(format!("internal codegen error: bad unary op {op:?}")),
            };
            Ok((expr_type.clone(), rendered))
        }

        AstKind::AsOp { expr, op, src_type } => compile_cast(fctx, expr, op, src_type),

        AstKind::FuncCall { name, args } => compile_expr_call(fctx, name, args, false),

        AstKind::BinaryOp {
            left,
            op,
            right,
            left_type,
            right_type,
        } => compile_binary_op(fctx, left, op, right, left_type, right_type),

        AstKind::ArrayLiteral { values } => compile_array_literal(fctx, values),

        AstKind::ArrayFill { size, value } => compile_array_fill(fctx, size, value),

        AstKind::ArrayGet { name, index } => {
            let ty = fctx.lookup(name)?;
            let elem = match &ty {
                TypesCheck::Array(inner) => (**inner).clone(),
                _ => {
                    return Err(format!(
                        "internal codegen error: ArrayGet on non-array variable '{name}'"
                    ));
                }
            };
            let suffix = array_elem_suffix(&elem);
            let (_, idx_code) = compile_expr(fctx, index)?;
            Ok((
                elem,
                format!("cyl_array_{suffix}_get({}, {idx_code})", c_name(name)),
            ))
        }

        AstKind::StructGet { name, index } => {
            let struct_ty = fctx.lookup(name)?;
            let struct_name = match &struct_ty {
                TypesCheck::Struct(name) => name,
                other => {
                    return Err(format!(
                        "internal codegen error: StructGet on non-struct type {other:?}"
                    ));
                }
            };
            let field_ty = fctx
                .prog
                .struct_fields(struct_name)?
                .iter()
                .find(|(field_name, _)| field_name == index)
                .map(|(_, ty)| ty.clone())
                .ok_or_else(|| {
                    format!(
                        "internal codegen error: unknown field '{index}' on struct '{struct_name}'"
                    )
                })?;
            let field_expr = format!("{}.{}", c_name(name), c_field_name(index));
            Ok((
                field_ty.clone(),
                clone_expr(fctx.prog, &field_ty, &field_expr),
            ))
        }

        other => Err(format!(
            "internal codegen error: unexpected expression-position node {other:?}"
        )),
    }
}

fn compile_cast(
    fctx: &mut FuncCtx,
    expr: &AstKind,
    op: &Cast,
    src_type: &TypesCheck,
) -> Result<(TypesCheck, String), String> {
    let (_, code) = compile_expr(fctx, expr)?;
    let (dst, rendered) = match (op, src_type) {
        (Cast::String, TypesCheck::Int) => {
            (TypesCheck::String, format!("cyl_int_to_string({code})"))
        }
        (Cast::String, TypesCheck::Float) => {
            (TypesCheck::String, format!("cyl_float_to_string({code})"))
        }
        (Cast::String, TypesCheck::Boolean) => {
            (TypesCheck::String, format!("cyl_bool_to_string({code})"))
        }

        (Cast::Int, TypesCheck::Float) => (TypesCheck::Int, format!("((cyl_int)({code}))")),
        (Cast::Int, TypesCheck::Boolean) => (TypesCheck::Int, format!("((cyl_int)({code}))")),
        (Cast::Int, TypesCheck::String) => (TypesCheck::Int, format!("cyl_string_to_int({code})")),

        (Cast::Float, TypesCheck::Int) => (TypesCheck::Float, format!("((double)({code}))")),
        (Cast::Float, TypesCheck::Boolean) => (TypesCheck::Float, format!("((double)({code}))")),
        (Cast::Float, TypesCheck::String) => {
            (TypesCheck::Float, format!("cyl_string_to_float({code})"))
        }

        (Cast::Boolean, TypesCheck::Int) => {
            (TypesCheck::Boolean, format!("((cyl_bool)(({code}) != 0))"))
        }
        (Cast::Boolean, TypesCheck::Float) => (
            TypesCheck::Boolean,
            format!("((cyl_bool)(({code}) != 0.0))"),
        ),
        (Cast::Boolean, TypesCheck::String) => {
            (TypesCheck::Boolean, format!("cyl_string_to_bool({code})"))
        }

        _ => {
            return Err(format!(
                "internal codegen error: unsupported cast {op:?} from {src_type:?}"
            ));
        }
    };
    Ok((dst, rendered))
}

fn compile_expr_call(
    fctx: &mut FuncCtx,
    name: &str,
    args: &[AstKind],
    in_stmt_position: bool,
) -> Result<(TypesCheck, String), String> {
    match name {
        "input" => return Ok((TypesCheck::String, "cyl_builtin_input()".to_owned())),
        "sin" | "cos" | "sqrt" => {
            let (_, a) = compile_expr(fctx, &args[0])?;
            return Ok((TypesCheck::Float, format!("cyl_builtin_{name}({a})")));
        }
        "shell" => {
            let (_, a) = compile_expr(fctx, &args[0])?;
            return Ok((TypesCheck::Int, format!("cyl_builtin_shell({a})")));
        }
        "unix_time" => {
            return Ok((TypesCheck::Int, "cyl_builtin_unix_time()".to_owned()));
        }
        "sleep" => {
            let (_, a) = compile_expr(fctx, &args[0])?;
            if !in_stmt_position {
                return Err(
                    "internal codegen error: sleep() used in expression position (validator should have rejected this)"
                        .to_owned(),
                );
            }
            return Ok((TypesCheck::Boolean, format!("cyl_builtin_sleep({a})")));
        }
        "len" => {
            let arg_ty = infer_expr_type(fctx, &args[0])?;
            let elem = match arg_ty {
                TypesCheck::Array(inner) => *inner,
                _ => {
                    return Err(
                        "internal codegen error: len() called on a non-array argument".to_owned(),
                    );
                }
            };
            let suffix = array_elem_suffix(&elem);
            let a = compile_borrow_expr(fctx, &args[0])?;
            return Ok((
                TypesCheck::Int,
                format!("((cyl_int)cyl_array_{suffix}_len({a}))"),
            ));
        }
        _ => {}
    }

    let (params, ret) = fctx
        .prog
        .funcs
        .get(name)
        .cloned()
        .ok_or_else(|| format!("internal codegen error: unknown function '{name}'"))?;

    if params.len() != args.len() {
        return Err(format!(
            "internal codegen error: call to '{name}' has {} args, expected {}",
            args.len(),
            params.len()
        ));
    }

    let mut rendered_args = Vec::with_capacity(args.len());
    for arg in args {
        let (_, code) = compile_expr(fctx, arg)?;
        rendered_args.push(code);
    }

    let ret_check = if matches!(ret, ReturnType::Void) {
        if !in_stmt_position {
            return Err(format!(
                "internal codegen error: call to void function '{name}' used in expression position"
            ));
        }
        TypesCheck::Boolean
    } else {
        return_type_to_check(&ret)
    };

    Ok((
        ret_check,
        format!("{}({})", c_func_name(name), rendered_args.join(", ")),
    ))
}

fn compile_borrow_expr(fctx: &FuncCtx, node: &AstKind) -> Result<String, String> {
    match node {
        AstKind::Ident(name) => {
            let _ = fctx.lookup(name)?;
            if fctx.is_const(name) {
                Ok(c_const_name(name))
            } else {
                Ok(c_name(name))
            }
        }
        AstKind::StructGet { name, index } => {
            let struct_ty = fctx.lookup(name)?;
            let struct_name = match &struct_ty {
                TypesCheck::Struct(name) => name,
                other => {
                    return Err(format!(
                        "internal codegen error: StructGet on non-struct type {other:?}"
                    ));
                }
            };
            let _ = fctx
                .prog
                .struct_fields(struct_name)?
                .iter()
                .find(|(field_name, _)| field_name == index)
                .ok_or_else(|| {
                    format!(
                        "internal codegen error: unknown field '{index}' on struct '{struct_name}'"
                    )
                })?;
            Ok(format!("{}.{}", c_name(name), c_field_name(index)))
        }
        other => Err(format!(
            "internal codegen error: len() needs a named array, got {other:?}"
        )),
    }
}

fn infer_expr_type(fctx: &FuncCtx, node: &AstKind) -> Result<TypesCheck, String> {
    match node {
        AstKind::Ident(name) => fctx.lookup(name),

        AstKind::Int(_) => Ok(TypesCheck::Int),
        AstKind::Float(_) => Ok(TypesCheck::Float),
        AstKind::Boolean(_) => Ok(TypesCheck::Boolean),
        AstKind::String(_) => Ok(TypesCheck::String),

        AstKind::BinaryOp {
            op,
            left_type,
            right_type,
            ..
        } => binary_op_result_type(op, left_type, right_type),
        AstKind::UnaryOp { expr_type, .. } => Ok(expr_type.clone()),
        AstKind::AsOp { op, .. } => Ok(match op {
            Cast::String => TypesCheck::String,
            Cast::Int => TypesCheck::Int,
            Cast::Float => TypesCheck::Float,
            Cast::Boolean => TypesCheck::Boolean,
        }),

        AstKind::ArrayLiteral { values } => {
            let first = values
                .first()
                .ok_or_else(|| "internal codegen error: empty array literal".to_owned())?;
            Ok(TypesCheck::Array(Box::new(infer_expr_type(fctx, first)?)))
        }
        AstKind::ArrayFill { value, .. } => {
            Ok(TypesCheck::Array(Box::new(infer_expr_type(fctx, value)?)))
        }
        AstKind::ArrayGet { name, .. } => match fctx.lookup(name)? {
            TypesCheck::Array(inner) => Ok(*inner),
            other => Err(format!(
                "internal codegen error: ArrayGet on non-array type {other:?}"
            )),
        },
        AstKind::StructGet { name, index } => {
            let struct_ty = fctx.lookup(name)?;
            let struct_name = match &struct_ty {
                TypesCheck::Struct(name) => name,
                other => {
                    return Err(format!(
                        "internal codegen error: StructGet on non-struct type {other:?}"
                    ));
                }
            };
            fctx.prog
                .struct_fields(struct_name)?
                .iter()
                .find(|(field_name, _)| field_name == index)
                .map(|(_, ty)| ty.clone())
                .ok_or_else(|| {
                    format!(
                        "internal codegen error: unknown field '{index}' on struct '{struct_name}'"
                    )
                })
        }
        AstKind::FuncCall { name, .. } => {
            let (_, ret) = fctx
                .prog
                .funcs
                .get(name)
                .ok_or_else(|| format!("internal codegen error: unknown function '{name}'"))?;
            Ok(return_type_to_check(ret))
        }
        other => Err(format!(
            "internal codegen error: cannot infer type of {other:?} for len()"
        )),
    }
}

fn compile_array_literal(
    fctx: &mut FuncCtx,
    values: &[AstKind],
) -> Result<(TypesCheck, String), String> {
    if values.is_empty() {
        return Err(
            "internal codegen error: empty array literal (validator should reject this via errors::A48)"
                .to_owned(),
        );
    }
    let elem_ty = infer_expr_type(fctx, &values[0])?;
    let suffix = array_elem_suffix(&elem_ty);

    let tmp = fctx.fresh_tmp("arr");
    let mut parts = vec![format!(
        "({tmp} = cyl_array_{suffix}_new({}))",
        values.len()
    )];
    for (i, v) in values.iter().enumerate() {
        let (_, code) = compile_expr(fctx, v)?;
        parts.push(format!("cyl_array_{suffix}_set({tmp}, {i}, {code})"));
    }
    parts.push(tmp.clone());

    let array_ty = TypesCheck::Array(Box::new(elem_ty));
    fctx.hoisted.push((tmp, array_ty.clone()));

    Ok((array_ty, format!("({})", parts.join(", "))))
}

fn compile_array_fill(
    fctx: &mut FuncCtx,
    size: &AstKind,
    value: &AstKind,
) -> Result<(TypesCheck, String), String> {
    let elem_ty = infer_expr_type(fctx, value)?;
    let suffix = array_elem_suffix(&elem_ty);
    let (_, size_code) = compile_expr(fctx, size)?;
    let (_, value_code) = compile_expr(fctx, value)?;
    let array_ty = TypesCheck::Array(Box::new(elem_ty));
    Ok((
        array_ty,
        format!("cyl_array_{suffix}_fill({size_code}, {value_code})"),
    ))
}

fn binary_op_result_type(
    op: &Token,
    left_type: &TypesCheck,
    right_type: &TypesCheck,
) -> Result<TypesCheck, String> {
    Ok(match op {
        Token::Or | Token::And => TypesCheck::Boolean,

        Token::Plus => match (left_type, right_type) {
            (TypesCheck::Int, TypesCheck::Int) => TypesCheck::Int,
            (TypesCheck::Float, TypesCheck::Float) => TypesCheck::Float,
            (TypesCheck::String, TypesCheck::String)
            | (TypesCheck::String, TypesCheck::Int)
            | (TypesCheck::String, TypesCheck::Float)
            | (TypesCheck::Int, TypesCheck::String)
            | (TypesCheck::Float, TypesCheck::String) => TypesCheck::String,
            _ => {
                return Err(format!(
                    "internal codegen error: bad '+' operand types {left_type:?}/{right_type:?}"
                ));
            }
        },
        Token::Minus => match left_type {
            TypesCheck::Float => TypesCheck::Float,
            _ => TypesCheck::Int,
        },
        Token::Multiply => match (left_type, right_type) {
            (TypesCheck::Int, TypesCheck::Int) => TypesCheck::Int,
            (TypesCheck::Float, TypesCheck::Float) => TypesCheck::Float,
            (TypesCheck::String, TypesCheck::Int) | (TypesCheck::Int, TypesCheck::String) => {
                TypesCheck::String
            }
            _ => {
                return Err(format!(
                    "internal codegen error: bad '*' operand types {left_type:?}/{right_type:?}"
                ));
            }
        },
        Token::Divide | Token::Mod => match left_type {
            TypesCheck::Float => TypesCheck::Float,
            _ => TypesCheck::Int,
        },

        Token::Equal
        | Token::NotEqual
        | Token::Greater
        | Token::Less
        | Token::GreaterEqual
        | Token::LessEqual => TypesCheck::Boolean,

        Token::BitAnd | Token::BitOr | Token::BitXor | Token::BitRight | Token::BitLeft => {
            TypesCheck::Int
        }

        _ => {
            return Err(format!(
                "internal codegen error: unsupported binary op {op:?}"
            ));
        }
    })
}

fn compile_binary_op(
    fctx: &mut FuncCtx,
    left: &AstKind,
    op: &Token,
    right: &AstKind,
    left_type: &TypesCheck,
    right_type: &TypesCheck,
) -> Result<(TypesCheck, String), String> {
    let (_, l) = compile_expr(fctx, left)?;
    let (_, r) = compile_expr(fctx, right)?;

    let result_ty = binary_op_result_type(op, left_type, right_type)?;

    let rendered = match op {
        Token::Or => format!("(({l}) || ({r}))"),
        Token::And => format!("(({l}) && ({r}))"),

        Token::Plus => match (left_type, right_type) {
            (TypesCheck::Int, TypesCheck::Int) => format!("(({l}) + ({r}))"),
            (TypesCheck::Float, TypesCheck::Float) => format!("(({l}) + ({r}))"),
            (TypesCheck::String, TypesCheck::String) => format!("cyl_string_concat({l}, {r})"),
            (TypesCheck::String, TypesCheck::Int) => format!("cyl_string_concat_int({l}, {r})"),
            (TypesCheck::String, TypesCheck::Float) => format!("cyl_string_concat_float({l}, {r})"),
            (TypesCheck::Int, TypesCheck::String) => {
                format!("cyl_string_concat_int_rev({l}, {r})")
            }
            (TypesCheck::Float, TypesCheck::String) => {
                format!("cyl_string_concat_float_rev({l}, {r})")
            }
            _ => unreachable!("binary_op_result_type already validated '+' operand types"),
        },
        Token::Minus => format!("(({l}) - ({r}))"),
        Token::Multiply => match (left_type, right_type) {
            (TypesCheck::Int, TypesCheck::Int) => format!("(({l}) * ({r}))"),
            (TypesCheck::Float, TypesCheck::Float) => format!("(({l}) * ({r}))"),
            (TypesCheck::String, TypesCheck::Int) => format!("cyl_string_repeat({l}, {r})"),
            (TypesCheck::Int, TypesCheck::String) => format!("cyl_string_repeat({r}, {l})"),
            _ => unreachable!("binary_op_result_type already validated '*' operand types"),
        },
        Token::Divide => match left_type {
            TypesCheck::Float => format!("(({l}) / ({r}))"),
            _ => format!("cyl_checked_div({l}, {r})"),
        },
        Token::Mod => match left_type {
            TypesCheck::Float => format!("fmod(({l}), ({r}))"),
            _ => format!("cyl_checked_mod({l}, {r})"),
        },

        Token::Equal => cmp_expr(left_type, "==", &l, &r, "cyl_string_eq"),
        Token::NotEqual => cmp_expr(left_type, "!=", &l, &r, "cyl_string_ne"),
        Token::Greater => cmp_expr(left_type, ">", &l, &r, "cyl_string_gt"),
        Token::Less => cmp_expr(left_type, "<", &l, &r, "cyl_string_lt"),
        Token::GreaterEqual => cmp_expr(left_type, ">=", &l, &r, "cyl_string_ge"),
        Token::LessEqual => cmp_expr(left_type, "<=", &l, &r, "cyl_string_le"),

        Token::BitAnd => format!("(({l}) & ({r}))"),
        Token::BitOr => format!("(({l}) | ({r}))"),
        Token::BitXor => format!("(({l}) ^ ({r}))"),
        Token::BitRight => format!("(({l}) >> ({r}))"),
        Token::BitLeft => format!("(({l}) << ({r}))"),

        _ => unreachable!("binary_op_result_type already rejected unsupported ops"),
    };

    Ok((result_ty, rendered))
}

fn cmp_expr(left_type: &TypesCheck, c_op: &str, l: &str, r: &str, string_fn: &str) -> String {
    match left_type {
        TypesCheck::String => format!("{string_fn}({l}, {r})"),
        _ => format!("(({l}) {c_op} ({r}))"),
    }
}
